### ISSUE TITLE
Speed limit panel and screen resolution over FullHD

### ISSUE THREAD

**Issue by MacSergey** [CitiesSkylinesMods/TMPE#935] opened 2020-06-11 14:22 UTC
If screen resolution over FullHD - 2K or 4K, Unable to move speed limit panel beyond FHD resolution

Example 2K: cant move it further to the right or down
![image](https://user-images.githubusercontent.com/20316130/84397913-ed0ca980-ac07-11ea-86cb-3b16599a3f5c.png)

**Comment by aubergine10** [comment] 2020-06-11 14:29
Confirmed - but duplicate of #573

**Closed by aubergine10** 2020-06-11 14:29 UTC
Labels: BUG, SPEED LIMITS, UI, confirmed, duplicate
