### ISSUE TITLE
Field '.PathUnit.m_vehicleTypes' not found. [System.MissingFieldException] in Vanilla

### ISSUE THREAD

**Issue by awiebe** [CitiesSkylinesMods/TMPE#797] opened 2020-03-28 13:02 UTC
Cities just keeps throwing this exception, once in game, making it impossible to do anything except kill it.
```
Field '.PathUnit.m_vehicleTypes' not found. [System.MissingFieldException]
```
Presumably this is because something about the traffic manager expects some data that is not available on vehicles without very specific expansions.

Ideally this part of the routing strategy should be ignored if these fields are unavailable, and this should be checked once on load.

**Comment by krzychu124** [comment] 2020-03-28 13:52
Hi, issues is known and it won't be fixed in old version of  **Traffic Manager (v.10.20)**
Follow this steps to switch to newer version:
- Close game,
- Unsubscribe all other versions on Traffic Manager including old, obsolete [Traffic Manager (v10.20)](https://steamcommunity.com/sharedfiles/filedetails/?id=583429740)
- Subscribe to [TM:PE V11](https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252)

**Comment by alxv2003** [comment] 2020-03-28 16:44
`Field '.PathUnit.m_vehicleTypes' not found. [System.MissingFieldException]

Details:
No details`

Also getting this, with TM:PE V11 (one linked above).  No other external mods installed in game, fresh game install.

**Comment by krzychu124** [comment] 2020-03-28 16:46
@alxv2003 drag&drop `output_log.txt` and `TMPE.log` [Info where to find logs](https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Cities-Skylines-log-file)

**Comment by alxv2003** [comment] 2020-03-28 18:07
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4397607/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4397608/TMPE.log)

**Comment by Xyrhenix** [comment] 2020-03-28 18:19
You 100% **are** using an outdated version of TM:PE.
From TMPE log:
```
Info 18.1273013: TM:PE enabled. Version 11.1.0, Build 11.1.0.36445 STABLE for game version 1.12.3-f2
```

From output log:
```
Game Version: 1.13.0-f7-steam-win
```

Please ensure you're running the latest version of TM:PE. It should read version 11.**2**.x.

**Comment by aubergine10** [comment] 2020-03-28 18:34
Use the mod compatibility checker, it will list any problems with your subscribed mods:

https://steamcommunity.com/sharedfiles/filedetails/?id=2034713132

**Comment by krzychu124** [comment] 2020-03-28 19:08
**All versions** released before Sunset Harbor **are incompatible** with latest version of game **v1.13.0**

Also latest version of TM:PE - **v11.2.0** **is incompatible** with **all previous versions** of the game **<1.12.X**

**Comment by aubergine10** [comment] 2020-04-21 03:48
Closing this as I think everyone has updated to v11 now (if not please let us know).

**Closed by aubergine10** 2020-04-21 03:48 UTC
Labels: awaiting feedback

**Comment by thilinadinith** [comment] 2020-04-30 18:15
still the issue is there with v11.4.0 :(  cities v1.12.0-f5

**Comment by krzychu124** [comment] 2020-04-30 18:24
@thilinadinith you are using old version of the game.
All legal sources where you can get the game, updated it to the latest version which is **1.13.0-f8** 
https://github.com/CitiesSkylinesMods/TMPE#support-policy

**Comment by lowasser** [comment] 2022-01-25 17:10
Getting this issue today as soon as I installed Airports.  Everything seems fully up to date, including both TM:PE and the base game.

[TMPE](https://gist.github.com/lowasser/3954f42c29ef7bdfd9b46a3b78be858e)
[output.log](https://gist.github.com/lowasser/560d474d63b96262a95b2747632d117b)

**Comment by krzychu124** [comment] 2022-01-25 17:20
I can assure you don't have this issue. 
Your issue is a result of not yet compatible version of IPT2 (Improved Public Transport 2). Disable that mod and wait for the update
