### ISSUE TITLE
Hot reload crashes with error too many threads

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#717] opened 2020-02-19 17:08 UTC
When I hot reload a lot I get error "too many threads" and then the game crashes. 

my memory is vague. I don't remember if I was swapping the DLL while the previous one was being loaded. 

This doesn't happen too often though. 

might be related to https://github.com/CitiesSkylinesMods/TMPE/pull/640/files/5a3ef25473a3696012317422aafbbd4e3bad59c2#r375479944 and https://github.com/CitiesSkylinesMods/TMPE/pull/640#issuecomment-583705596

we need to check stack trace and look for thread leak. 

unloading DLL only calls OnDisable. It does not call the OnRelease() of loading extension. What does it do to threading extension? In any case the OnRelease() override of our threading extension is empty so I am not sure if that makes a difference. I thinl the game no longer calls overrides from old threading extension DLL ... I hope.

EDIT:
Fixing this is not so important in itself but it might help us improve our code and hunt down some other hidden bugs.

**Comment by kianzarrin** [comment] 2020-02-19 17:09
setting this to low priority because it does not happen often and its only a dev thing.

Investigating this might help us reduce our resource leak (or is it called thread leak ?) when loading another game or when quieting to main menu.

**Comment by aubergine10** [comment] 2020-02-19 17:39
The game itself mem leaks when quitting to main menu because it doesn't acutally unload the previous scene.

**Comment by krzychu124** [comment] 2020-02-19 17:42
> The game itself mem leaks when quitting to main menu because it doesn't acutally unload the previous scene.

What do you mean by that?

**Comment by aubergine10** [comment] 2020-02-19 17:43
Can't remember who said it, one of the Paradox people I think; that the game doesn't properly unload the previous scene when exiting to main menu.

**Comment by aubergine10** [comment] 2020-02-22 09:08
Was this issue caused by double-reload problem described in https://github.com/CitiesSkylinesMods/TMPE/issues/718#issuecomment-589812785 ?

**Comment by kianzarrin** [comment] 2020-02-22 09:52
I Do not know @aubergine10 . Its not all that easy to reproduce. I shall see. I totally forgot to add crash log. I will add logs if/when it happens next.

**Comment by aubergine10** [comment] 2020-02-22 18:20
were those the crash logs in the PR that just got merged? #725

**Comment by kianzarrin** [comment] 2020-02-22 19:39
> @aubergine10  not sure which crash logs are you talking about but the logs in #725 were not crash logs. they were success logs.

I haven't  got a crash log yet.

**Comment by kianzarrin** [comment] 2020-03-01 11:04
related https://github.com/CitiesSkylinesMods/TMPE/issues/730#issuecomment-593083764

**Comment by kianzarrin** [comment] 2020-04-18 05:16
I closed this because I have not observed this since I have fixed the Double hot reload issue.

**Closed** 2020-04-18 05:16 UTC
Labels: BUG, low priority

**Comment by aubergine10** [comment] 2020-04-18 13:45
@kianzarrin do you remember the issue/pr number where that change was made (just so the tickets can be linked). There are several issues mentioned above, was it one of those?

**Comment by kianzarrin** [comment] 2020-04-18 17:51
#725 was the PR that seems to have fixed this issue.
