### ISSUE TITLE
Cargo Import not working

### ISSUE THREAD

**Issue by LordSmeghead** [CitiesSkylinesMods/TMPE#978] opened 2020-07-16 18:17 UTC
### Describe the problem

For my current city I'm unable to recieve any imports for the commercial or industrial areas either by road or rail (I don't have a cargo harbour). No cargo trains or vehicles spawn with goods or materials directed into the city, however dummy traffic is still able to spawn. I am also recieving the following error within the game using the extended error outputs;

An exception occured during VehicleAI simulation step.
Asset: Forestry Truck
VehicleID: 10312
Type: CargoTruckAI
Severity: High

System.IndexOutOfRangeException: Array index is out of range.
at PassengerPlaneAI.StartPathFind (uint16,Vehicle+) <0x002a8>
at PassengerPlaneAI.SetTarget (uint16,Vehicle+,uint16) <0x00122>
at (wrapper dynamic-method) CargoTruckAI.DMD<DMD<ChangeVehicleType_Patch2>?1253452672..ChangeVehicleType_Patch2> (VehicleInfo,uint16,Vehicle+,PathUnit/Position,uint) <0x00960>
at CargoTruckAI.ChangeVehicleType (uint16,Vehicle+,PathUnit/Position,uint) <0x0004a>
at TrafficManager.Custom.AI.CustomVehicleAI.CustomUpdatePathTargetPositions (uint16,Vehicle+,UnityEngine.Vector3,int+,int,single,single) <0x02554>
at CarAI.SimulationStep (uint16,Vehicle+,Vehicle/Frame+,uint16,Vehicle+,int) <0x00880>
at VehicleAI.SimulationStep (uint16,Vehicle+,uint16,Vehicle+,int) <0x003b9>
at TrafficManager.Custom.AI.CustomCarAI.CustomSimulationStep (uint16,Vehicle+,UnityEngine.Vector3) <0x005cf>
at TrafficManager.Custom.AI.CustomCargoTruckAI.CustomSimulationStep (uint16,Vehicle+,UnityEngine.Vector3) <0x00199>
at HealkitMod.Patches.VehicleManagerPatch.SimulationStep (VehicleAI,uint16,Vehicle+,UnityEngine.Vector3) <0x00062>

This seems to occur for each alternate type of vanilla cargo vehicle. I have tried launching the save in safe modes using LSM but this has not fixed the issue and I have also tried the broken node finder to no success (in terms of seeing if it was a cause, no broken nodes were found). 

### Steps to reproduce

Since it occurs due to import of cargo all that needs to be done is to wait until the error appears.

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4933367/output_log.txt)

**Comment by LordSmeghead** [comment] 2020-07-16 18:18
I've found this steam thread as well with a seemingly identical issue:
https://steamcommunity.com/app/255710/discussions/0/2296220207949815906/

**Comment by krzychu124** [comment] 2020-07-16 18:27
Hi, I need savegame to reproduce that issue. [Guide how to share saved game](https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Savegame-on-Steam)

**Comment by LordSmeghead** [comment] 2020-07-16 19:08
https://steamcommunity.com/sharedfiles/filedetails/?id=2168233496

Mods and Asset list .txt:
[Mod Asset List.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4933664/Mod.Asset.List.txt)

**Comment by krzychu124** [comment] 2020-07-18 20:37
Hmm, I tried you savegame, downloaded all assets and mods and I can't reproduce issue. 
I was running simulation at full speed more than 30 min and nothing, not even one single error appeared. Also I didn't spot any issues with import/export
Make sure that all necessary assets are enabled, like train stations, because if missing, game might throw some errors and skip whatever is doing at a time of error, including sending trucks to other buildings.

**Comment by LordSmeghead** [comment] 2020-07-19 13:04
Okay thank you so much for having a look, I've had a further check and it turns out there's something impacting the entire vehicle path finding AI all together, no matter whether it's through TMPE or vanilla pathfinding. Anyway thank you for the assistance (and cheers for maintaining this excellent mod).

**Comment by krzychu124** [comment] 2020-08-04 22:45
I'm closing this issue. If problem returns, please reopen it again 😉

**Closed by krzychu124** 2020-08-04 22:45 UTC
Labels: BUG

**Comment by Xyrhenix** [comment] 2020-08-05 01:08
Of importance: Enhanced District Services (ID: 1922400472) is known to ruin industry area imports (both vanilla and with industries DLC). Many people in the mod's comments section have commented with industry supply problems, some saying that an older version of the mod appears to work fine. I know this from experience, as subscribing and enabling the mod destroyed my city's economy and removing the mod caused instant improvement.

**Comment by aubergine10** [comment] 2020-08-05 14:07
Do you have an airport or passenger helicopter outside the central 25 tile area? It's known to break 81 Tiles mod.
