### ISSUE TITLE
Reset configuration (whole/partially)

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#127] opened 2019-03-03 02:59 UTC
http://steamcommunity.com/workshop/filedetails/discussion/583429740/333656722984247924/

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/24

**Comment by aubergine10** [comment] 2020-02-24 01:09
Closing as duplicate of #281

**Closed by aubergine10** 2020-02-24 01:09 UTC
Labels: Settings, duplicate, enhancement
