### ISSUE TITLE
Differentiate between all three states in junction restrictions tool

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#239] opened 2019-03-16 00:16 UTC
Currently the UI only models two states for each junction restriction: **allowed** and **prohibited**
But the underlying model knows three states: **allowed**, **prohibited**, and **undefined** (default: **undefined**)

The missing **undefined** state representation in the UI causes problems when players first set/unset an individual restriction (e.g. allow u-turns, then disallow them again) and later activate the corresponding city-wide option (e.g. "Vehicles may do u-turns at junctions") in the options dialog.

Because the state can only be set to either **allowed** or **prohibited** in the UI overlay, setting the city-wide option does not have an effect for any touched junction.

The UI should represent all three possible states. The **undefined** state should be selectable (similarly to the priority signs tool where the user can cycle through the available signs) and should also be represented by a meaningful overlay icon in the junction restrictions tool.

**Comment by aubergine10** [comment] 2019-03-16 03:49
I added a templates folder a while back with the backgrounds for enabled (green circle) and disabled (red circle with slash) - want me to ponder what 'default' state would look like and do some templates?

Could just be a white circle, or maybe with dashed grey outline?

No idea what the default state for ped crossings would look like though...

Also... should there be three states? I'm thinking in terms of savegame data size and also things like branch predication here... Would it be better to have two states:

1. Default (as per mod settings)
2. Opposite of default (ie. default setting overriden at the junction level)

That line of thinking could then be extended: Flatten the junction feature data while playing the game (no more 'if not set go look at defaults'), then when saving game only store stuff that isn't the default.

**Comment by kianzarrin** [comment] 2020-04-17 08:29
this is fixed as duplicate of #623. Do you agree @aubergine10 ?

**Closed by kianzarrin** 2020-04-17 08:29 UTC
Labels: JUNCTION RESTRICTIONS, UI, enhancement
