### ISSUE TITLE
Speed limits UI is huge

### ISSUE THREAD

**Issue by RenaKunisaki** [CitiesSkylinesMods/TMPE#299] opened 2019-04-30 23:00 UTC
https://steamcommunity.com/sharedfiles/filedetails/?id=1728287987 the speed limit icons are gigantic. Could stand to be the same size as the main panel.

**Comment by aubergine10** [comment] 2019-04-30 23:36
I also had this problem when I was on previous computer - it would fill half the screen. Yup, we're planning on redoing the whole UI.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/128

**Comment by aubergine10** [comment] 2019-05-01 15:37
Duplicate of #84 

@RenaKunisaki I've marked this as duplicate as the work is already planned as part of #84 - please subscribe that issue instead to monitor progress.

**Comment by kvakvs** [comment] 2019-09-16 10:37
For now tried the following:

* reducing the texture sizes: reducing too much creates ugly white pixel artifacts around each sign, so had to stop at 70px which looks kind of OK
* removing flexible spacers between signs and on the left
* stacking the controls below, one above another

This allowed to reduce the window size. More can be done of course, i will continue. Can also try and replace checkboxes with icon buttons. Also should try and scale using the fixed pixel size as reference for 1920x1080 screen, and scaling up or down if the user has different screen.

**Comment by aubergine10** [comment] 2019-09-17 02:34
I think the flat buttons I'm working on might help here.

**Comment by kianzarrin** [comment] 2020-02-16 07:01
see http://www.41post.com/3816/programming/unity-scaling-the-gui-based-on-the-screen-resolution

> @kvakvs GUI resolution should be done somewhat globally in a tool class, and then applied to all GUI windows. 

I can't see how @kvakvs suggestion would work in practice. either we have to implement a wrapper over all of GUI or our tool class would be limiting. I think we need a helper class that would provide some helper functions in this regard and maybe wrap a few commonly used GUI API.

**Comment by kvakvs** [comment] 2020-02-16 10:36
Yes there is going to be an UI builder helper and maybe a few new subclasses for common UI elements (buttons, panels, images etc), which will scale self properly. That's is the plan at least.

**Comment by aubergine10** [comment] 2021-12-10 21:43
This has been resolved by #1152, #1157, #1168 

Issue #1221 is tracking discussion of additional enhancements which may be made in future.

**Closed by aubergine10** 2021-12-10 21:43 UTC
Labels: duplicate, enhancement, UI, SPEED LIMITS
