### ISSUE TITLE
Vehicles that turn to a building must follow priority rules

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#135] opened 2019-03-03 03:31 UTC
see https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/32

copied from https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/57

---

Summary: If vehicles can cross oncoming traffic to enter a building, they should wait until there is a gap in that traffic before doing so.

**Comment by aubergine10** [comment] 2019-03-03 15:07
Related: #19 , #89

**Comment by aubergine10** [comment] 2021-12-09 00:42
Closing this old ticket; the issue is now being tracked in #1223

**Closed by aubergine10** 2021-12-09 00:42 UTC
Labels: feature, PRIORITY SIGNS
