### ISSUE TITLE
Copy-Paste

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#177] opened 2019-03-03 04:34 UTC
If possible, add configurable keyboard shortcuts for copy-paste of traffic lights (and, when applicable, lane connections, vehicle restrictions and so on). Also, having shortcuts to select a sub-tool (eg. lane connector, vehicle restrictor, etc) would also be useful.

The shortcuts would only be active while TM:PE menu is active, or whilst relevant sub-tool is active, etc.

Shortcuts should ideally be configurable in mod options.

Mods such as "Move It" and "Fine Road Tool" are good examples to refer to for this sort of stuff.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/153

**Comment by VictorPhilipp** [comment] 2019-03-03 04:34
Related to #103

**Comment by aubergine10** [comment] 2019-03-03 04:35
Could be done as part of #38 (UI overhaul).

**Comment by aubergine10** [comment] 2019-03-03 23:26
I think we should also start gathering user stories about what the feature should provide.

From LCOfficerUNIT97 (steam user):

> You should add something so you can copy and paste vehicle restrictions to roads, for large grid-like cities.

I've also seen people asking for priority sign propagation along roads - they were not aware that a feature already exists for that (part of UI overhaul will be creating some buttons to make such features more discoverable without requiring user to RTFM).

Many have also asked for copy/paste of speed limits (again, there is already some feature support in this respect) however on further discussion it turned out the real problem was the cumbersome default speed settings UI (see #84 for ideas on how to tackle that).

Other users have asked for copy/paste at junctions, which could obviously be problematic depending on number of roads at junction, etc.

**Comment by MichelArendt** [comment] 2019-12-17 15:01
It would help a lot for some way to copy/paste lane connections from junctions with the same setup!

**Comment by aubergine10** [comment] 2020-02-24 01:30
Keyboard shortcuts for tool selection are available in **Mod Options > TMPE > Keybinds** tab since v10.21. Likely we'll add some more see #720

Tool applicators are now widely covered by keyboard shortcuts: https://github.com/CitiesSkylinesMods/TMPE/wiki/Shortcuts

As such, going to refocus this issue #177 as tracking of ideas for copy/paste functionality.

**Comment by aubergine10** [comment] 2020-02-24 01:32
Duplicate of #154

Actually #154 is tracking ideas for copy/paste so closing this issue as duplicate.

**Closed by aubergine10** 2020-02-24 01:32 UTC
Labels: Keybinds, enhancement, low priority
