### ISSUE TITLE
'Array index is out of range' 

### ISSUE THREAD

**Issue by Remlej9** [CitiesSkylinesMods/TMPE#1195] opened 2021-11-14 20:39 UTC
I can't load my save after playing for a few hours, made no changes during this time but disabled a few mods after the issue started appearing, this is my logfile:

Simulation error: Array index is out of range.
  at NetManager+Data.Deserialize (ColossalFramework.IO.DataSerializer s) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode, ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode) [0x00000] in <filename unknown>:0 
  at LoadingManager+<LoadSimulationData>c__IteratorB.MoveNext () [0x00000] in <filename unknown>:0 
  at AsyncTask.Execute () [0x00000] in <filename unknown>:0   [Core]

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/7534621/output_log.txt)

I don't know if this is the right place to ask but if this is where I can get help, I want it. Thanks!

**Comment by krzychu124** [comment] 2021-11-14 20:51
> but disabled a few mods after the issue started appearing

Error is not caused by Traffic Manager, 100% sure because we don't touch how game is saving/loading data, Probably old mod changed savegame data and now you won't load that savegame without it.
The other option is that something went wrong while saving and now data is corrupted (it looks different than the game expects it to look like).

Anyways, out of scope, no signs in the log where the problem is.

**Comment by Remlej9** [comment] 2021-11-14 21:18
@krzychu124 I think I remember getting an error while saving but I didn't think much of it as it created a save anyways.
I guess I'll start a new save (create new ones all the time due to corruption like this so no problem) and be more observant on these errors before saving. Thanks!

**Comment by aubergine10** [comment] 2021-11-27 16:21
The [Compatibility Report](https://steamcommunity.com/sharedfiles/filedetails/?id=2633433869) mod in Steam Workshop can help track down outdated/broken mods which might result in that error. There's also a [page in our wiki](https://github.com/CitiesSkylinesMods/TMPE/wiki/Simulation-error-Array-index-is-out-of-range) with some other known causes and how to fix them - I've just updated it (see symptom 16 heading on that page) - namely, the Loading Screen Mod "Safe Mode" might help, and also use the Compatibility Report mod to check if you have any broken mods.

I'll close this issue 1195 for now as it looks like you already started a new city, but if you get similar errors maybe something in our [Troubleshooting guide](https://github.com/CitiesSkylinesMods/TMPE/wiki/Troubleshooting) will help. If you do find which mod or asset caused your save to break, please let us know and I'll update the guide as it will help other users who may encounter similar problems.

**Closed by aubergine10** 2021-11-27 16:21 UTC
Labels: wontfix, EXTERNAL, out of scope
