### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by whyper62** [CitiesSkylinesMods/TMPE#905] opened 2020-05-23 17:49 UTC
### Describe the problem

TMPE Labs crashed

### Steps to reproduce
Installed Mod MOM 

1. deinstall MOM -> it works fine
2. install MOM -> chance Labs into Stabel   up Now, no Errors seen
3. 

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4672239/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4672240/TMPE.log)

**Comment by krzychu124** [comment] 2020-05-23 18:00
It seems you are not reading mod descriptions...
Why do you have two versions of the mod subscribed??
If you want to change version you **have to** close game first then use Steam client to unsubscribe one and then subscribe to the other. If you do that while game is running you are calling for troubles.

Log contains a lot errors unrelated to TM:PE but worth fixing.
Use [Mod Compatibility Checker](https://steamcommunity.com/workshop/filedetails/?id=2034713132) to find issues with mod you subscribe and follow mod description to solve problems

**Comment by whyper62** [comment] 2020-05-23 20:45
First I `ve  installed the Labs Version and all will be fine. After I installed MOM i have trouble .
Then I Reabo the Lab and get the Stable Version, no mistakes appears . 
I can't detect duplicate mods in the log file, possibly by swapping labs for stable?
Subscribed is now only then Stable Version
also the recommented Files for TM:PE where installed.
It may be possible that i not exit to Desktop only to Main Menue , i try to make it better.

**Comment by krzychu124** [comment] 2020-05-23 20:59
The problem is if you changing versions when game is running you will end up with all versions loaded to memory. Unsubscribed mod is not unloaded from memory so we recommend closing game before switching versions

**Closed** 2021-07-30 21:15 UTC
Labels: BUG, COMPATIBILITY, EXTERNAL
