### ISSUE TITLE
ESC key not working

### ISSUE THREAD

**Issue by DregnRyder** [CitiesSkylinesMods/TMPE#1021] opened 2020-10-27 03:23 UTC
### Describe the problem
After installing TMPE: Labs, the ESC key does not close the main window for TMPE once opened. 
I have tried the ol' hard reset: exited game, un-subbed from LABS, opened game, created new save, exited game, re-subbed to LABS, restarted game. Same function. 

This is the case for BOTH LABS and STABLE versions. It started when I switced from Stable to Labs for the first time. Prior to this, Stable functioned properly.  

All other mods operate fine using the ESC key per my testing. 

### Steps to reproduce

1. Open the main TMPE pop-up menu with either a mouse click or toggle via key-bind (SHIFT+T). 
2. Press ESC (nothing happens). The pop-up menu stays open.
3. Close is only available via key-bind (SHIFT+T) or mouse click.

### Output Log: 
https://ufile.io/5da8px67

### Auto Repair Log: 
https://ufile.io/8nvcemnk

### Savegame: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2269067816
[AutoRepair.log](https://github.com/CitiesSkylinesMods/TMPE/files/5442754/AutoRepair.log)

### Notes or questions?
I have the AutoRepair log if you would like that as well. I have not seen any conflicting issues myself.

**Comment by kianzarrin** [comment] 2020-10-27 06:36
UnifiedUI mod will make sure ESC key works for every mod.

**Comment by krzychu124** [comment] 2020-10-27 13:56
Out of scope, issue caused by outdated, obsolete mod.
Complete unsubscribe [One-Way Street Arrows](https://steamcommunity.com/sharedfiles/filedetails/?id=420500168) you don't need that mod at all, because game already implements that feature.
Removing that mod subscription will improve game performance(that mod was spamming the log with errors) and **TM:PE** will start working normally :)

**Closed** 2020-10-27 13:56 UTC
Labels: Keybinds, out of scope, wontfix
