### ISSUE TITLE
The TM:PE menu refuses to open.

### ISSUE THREAD

**Issue by doctolad** [CitiesSkylinesMods/TMPE#1158] opened 2021-09-09 23:56 UTC
I'm on Cities:Skylines version 1.13.3-f9-steam-win with TM:PE v11.5.2 STABLE-hotfix-1 27/May/2021.

The TM:PE menu refuses to open, stopping me from making lane connections, timed traffic lights, etc. I'm not really good at reading log files and deducing what's wrong, but I feel like I've tried everything except reporting the problem. 

The first error that pops up in the log reads:

```
Error 101.3815524: While creating MainMenu: System.NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.UI.MainMenu.MainMenuWindow.SetupControls_DebugLabels (TrafficManager.U.UiBuilder`1 builder, ColossalFramework.UI.UIComponent stackUnder) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.MainMenu.MainMenuWindow.SetupControls (TrafficManager.U.UiBuilder`1 builder) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.MainMenu.MainMenuWindow.CreateMainMenuWindow () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.ModUI.CreateMainMenuButtonAndWindow () [0x00000] in <filename unknown>:0 
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.UI.ModUI.CreateMainMenuButtonAndWindow()
   at TrafficManager.UI.ModUI..ctor()
   at UnityEngine.GameObject.Internal_AddComponentWithType(System.Type )
   at UnityEngine.GameObject.AddComponent(System.Type componentType)
   at UnityEngine.GameObject.AddComponent()
   at TrafficManager.UI.ModUI.OnLevelLoaded()
   at TrafficManager.LoadingExtension.OnLevelLoaded(LoadMode mode)
   at LoadingWrapper.LoadingWrapper.OnLevelLoaded_Patch1(.LoadingWrapper , UpdateMode )
   at LoadingManager+<LoadLevelComplete>c__Iterator9.MoveNext()
   at LoadingManager.FpsBoosterUpdate()
   at BehaviourUpdater.Updater.Update()
```   
   Later on, this error appears and seems to repeat hundreds of times: 

```   
   GUI Error: System.NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.UI.TrafficManagerTool.OnToolGUIImpl (UnityEngine.Event e) [0x00000] in <filename unknown>:0 
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.UI.TrafficManagerTool.OnToolGUIImpl(UnityEngine.Event e)
   at TrafficManager.UI.TrafficManagerTool.OnToolGUI(UnityEngine.Event e)
   at ToolBase.OnGUI()
```

Again, I have no idea what's causing this, as I'm not good at reading error logs and stuff. I'm sorry if this issue has been resolved on another thread, but I couldn't find it in the trouble-shooting guide.

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/7140293/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/7140295/TMPE.log)

I hope the logs help. Sorry if this issue is really simple to fix, I just don't know how.

**Comment by kianzarrin** [comment] 2021-09-10 07:07
is it reliably reproducible?

**Comment by krzychu124** [comment] 2021-09-10 09:09
Probably because of:
```cs
IOException: Sharing violation on path C:\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\TMPE.log
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.StreamWriter..ctor (System.String path, Boolean append, System.Text.Encoding encoding, Int32 bufferSize) [0x00000] in <filename unknown>:0 
  at System.IO.StreamWriter..ctor (System.String path, Boolean append) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamWriter:.ctor (string,bool)
  at System.IO.File.AppendText (System.String path) [0x00000] in <filename unknown>:0 
  at CSUtil.Commons.Log.LogToFile (System.String log, LogLevel level) [0x00000] in <filename unknown>:0 
  at CSUtil.Commons.Log.InfoFormat (System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at TrafficManager.TrafficManagerMod.OnEnabled () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at ColossalFramework.Plugins.PluginManager.AddPlugins (System.Collections.Generic.Dictionary`2 plugins) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
ColossalFramework.Plugins.PluginManager:AddPlugins(Dictionary`2)
ColossalFramework.Plugins.PluginManager:LoadPlugins()
Starter:Awake()
```
Possible solutions
https://github.com/CitiesSkylinesMods/TMPE/wiki/System.IO.IOException

**Comment by doctolad** [comment] 2021-09-11 08:50
Thanks, the mod works now!

**Comment by krzychu124** [comment] 2021-09-11 20:54
Cool, closing the issue 😉

**Closed by krzychu124** 2021-09-11 20:54 UTC
