### ISSUE TITLE
Subscribing to node geometries fails

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#171] opened 2019-03-03 04:25 UTC
Two players (Rhowarion and surf2explore) report the following error:

```
The Mod D:\Steam\steamapps\workshop\content\255710\583429740 [CSUtil.CameraControl.dll, CSUtil.Commons.dll, TMPE.GenericGameBridge.dll, TMPE.CitiesGameBridge.dll, TrafficManager.dll] has caused an error [ModException] 

Details:
System.NullReferenceException: Object reference not set to an instance of an object
at TrafficManager.Manager.AbstractNodeGeometryObservingManager.SubscribeToNodeGeometry (UInt16 nodeId) [0x00000] in <filename unknown>:0
at TrafficManager.Manager.Impl.JunctionRestrictionsManager+JunctionRestrictionsNodeWatcher.OnLevelLoading () [0x00000] in <filename unknown>:0
at TrafficManager.Manager.Impl.JunctionRestrictionsManager.OnLevelLoading () [0x00000] in <filename unknown>:0
at TrafficManager.LoadingExtension.OnLevelLoaded (LoadMode mode) [0x00000] in <filename unknown>:0
at LoadingWrapper.OnLevelLoaded (UpdateMode mode) [0x00000] in <filename unknown>:0 
```

However, I am currently unable to identify the cause of this problem.

https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/139

**Comment by VictorPhilipp** [comment] 2019-03-03 04:25
The problem is that the SerializableDataExtension.OnLoadData() method is never called due to errors in other mods. These errors cause the game to skip this essential part of the loading procedure.
In the OnLoadData method, TMPE also intializes node and segment geometries.
The only thing that could be done is to move the relevant parts somewhere else, but even then loading custom data would be skipped.

**Comment by VictorPhilipp** [comment] 2019-03-03 04:25
Соединенные Штат also reported this error on the Steam Workshop page comments. I asked him to try disabling other mods to determine which one is causing the problem. Even if it's other mod problem, it would still be useful to let users know which mods conflict so they can more quickly work around the problem by disabling those mods.

**Comment by aubergine10** [comment] 2019-03-03 06:46
I've removed the 'wont fix' label - I think if possible we should find what mods cause the issue and then add them to incompatibility checker.

If this issue arises again, please let me know and I'll work with issue reporters to try and get details of what mods they use and do some testing to reproduce issue.

**Comment by krzychu124** [comment] 2021-07-30 22:08
No other reports since then. Not able to reproduce. Closing for now.

**Closed by krzychu124** 2021-07-30 22:08 UTC
Labels: Annoyance, COMPATIBILITY, EXTERNAL
