### ISSUE TITLE
Red Cars Parked on Empty Roads

### ISSUE THREAD

**Issue by chimerabyte** [CitiesSkylinesMods/TMPE#598] opened 2019-12-18 21:42 UTC
### Describe the problem

I'm seeing red cars parked along empty roads in my games sometimes. I've never had the vehicle wealthizer mod and I don't have it currently installed. I did have real time installed at one point, but I removed it and it happened even after removing that mod in a new game.

Mods active and installed: unlimited money/soil/ores (vanilla), tmpe labs, loading screen mod, WG realistic population, and achieve it.

### Steps to reproduce

1. make a new game, in my case the blackwoods map, with the listed mods above.
2. Start building roads, not even zoning anything, just planning out your map.
3. After building several roads, cars will just suddenly be parked there.

### Log files

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3980621/output_log.txt)
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3980624/TMPE.log)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=1939986003

### Screenshots?

https://imgur.com/8fNn0X0
(Not the same save-game, but it's from when the issue first appeared and I still had real-time installed)

### Notes or questions?

Going to maintenance and clicking on clear parked vehicles got rid of them. I don't know if they'll appear again when building more roads, but yeah.

**Comment by aubergine10** [comment] 2019-12-18 22:33
Just pasting some stuff from the dev chat:

> aubergine: The red car thing? I've heard of it several times in past, we tracked down one cause was Vehicle Wealthizer mod, but over past few years I've seen people report the issue that didn't have that mod. Still none the wiser as to what could cause it.
>  
> From memory parked cars aren't really cars; they all share the same object type but have different models. For example, if I use "Customize It Extended" mod to alter the name of any parked car, all parked cars get the same name. So maybe it's whatever code in game that sets the 'generic' parked car to look like a specific vehicle that's breaking somehow?
>  
> It could be used has some broken vehicle asset, and somehow that breaks the parked car vehicle choice? But why would such a bug always result in red cars? Or maybe it's something to do with colorization of the vehicles - maybe broken shader or something?

> krzychu: maybe dummy car asset is red?

> aubergine: i have vague recollections of a specific vehicle asset that thale5 (LSM mod dev) said the game required - maybe that has something to do with it? I'll see if I can find which asset it was....

> from example LSM skip.txt by thale5:
> > You should not skip Sedan because it is special in the game (used as a fallback vehicle).

**Comment by krzychu124** [comment] 2020-11-13 04:07
Closing. Feel free to reopen if issue persist.

**Closed by krzychu124** 2020-11-13 04:07 UTC
Labels: EXTERNAL, irreproducible

**Comment by kianzarrin** [comment] 2020-11-13 12:25
is it resolved?

**Comment by krzychu124** [comment] 2020-11-13 14:41
Check issue date, also no further responses, I can't reproduce issue using that savegame and never experienced such problem

**Comment by kianzarrin** [comment] 2021-01-21 06:03
@krzychu124 I faced this problem again:
![image](https://user-images.githubusercontent.com/26344691/105286348-c01d6d80-5bbe-11eb-873f-4825aaa0ccb7.png)
It is with the adaptive roads mod though.
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/5847204/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/5847205/output_log.txt)
but I have faced this problem a lot in the TMPE only mode too.
it seems to only happen when you create a + junction that is NOT connected to the highway as your first act.

**Comment by Elesbaan70** [comment] 2022-06-19 03:11
This Reddit comment claims to explain the root cause of this issue:

https://www.reddit.com/r/CitiesSkylines/comments/vf930o/comment/icv2dqc/?utm_source=share&utm_medium=web2x&context=3

**Comment by Elesbaan70** [comment] 2022-06-19 19:21
I've created a new issue for this which includes exact steps to reproduce. #1603
