### ISSUE TITLE
Another array index error

### ISSUE THREAD

**Issue by jaakattack** [CitiesSkylinesMods/TMPE#1051] opened 2021-01-31 06:27 UTC
Hey folks!

I'm also experiencing the Array index is out of range error. I checked your Wiki page and noticed that "symptom 2" pretty much suits my problem, and I tried all troubleshooting steps, except for reverting to a savegame from before the problem first occurred. I put a lot of work into the save in the meanwhile, so I'd love to avoid doing that if possible!

If you guys have any clues what might be going on in my logfile, I'd really appreciate a second set of eyes on it.

The short and sweet:

Simulation error: Array index is out of range.
  at PassengerTrainAI.SimulationStep (UInt16 vehicleID, .Vehicle& vehicleData, .Frame& frameData, UInt16 leaderID, .Vehicle& leaderData, Int32 lodPhysics) [0x00000] in <filename unknown>:0 
  at VehicleAI.SimulationStep (UInt16 vehicleID, .Vehicle& vehicleData, UInt16 leaderID, .Vehicle& leaderData, Int32 lodPhysics) [0x00000] in <filename unknown>:0 
  at TrafficManager.Custom.AI.CustomTrainAI.CustomSimulationStep (UInt16 vehicleId, .Vehicle& vehicleData, Vector3 physicsLodRefPos) [0x00000] in <filename unknown>:0 
  at VehicleManager.SimulationStepImpl (Int32 subStep) [0x00000] in <filename unknown>:0 
  at SimulationManagerBase`2[Manager,Properties].SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
  at VehicleManager.ISimulationManager.SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationStep () [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationThread () [0x00000] in <filename unknown>:0   [Core]

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/5899268/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/5899269/TMPE.log)

**Comment by krzychu124** [comment] 2021-01-31 16:21
Hello, 
enable **One-Way Train Tracks** mod because it's a dependency of one of your train stations (https://steamcommunity.com/sharedfiles/filedetails/?id=2209144173)

**Comment by jaakattack** [comment] 2021-02-01 05:18
> Hello,
> enable **One-Way Train Tracks** mod because it's a dependency of one of your train stations (https://steamcommunity.com/sharedfiles/filedetails/?id=2209144173)

Thanks for the tip. I enabled the One-Way Train Tracks mod, but it didn't fix the problem, unfortunately. Here are my updated output logs with the mod enabled.

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/5902013/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/5902014/output_log.txt)

**Comment by krzychu124** [comment] 2021-02-01 12:04
Could you try that again since enabling one-way tracks mod loaded all train/metro station? https://github.com/CitiesSkylinesMods/TMPE/wiki/Array-Index---Symptom-2

**Comment by jaakattack** [comment] 2021-02-03 08:16
Just tried it again with the one-way tracks enabled and all train/metro stations, but the problem persists.

**Comment by krzychu124** [comment] 2022-06-22 19:47
MOM mod is mentioned, looking at the stacktrace it might be broken asset. Since then a lot of code changed - irreproducible. Closing, reopen if problem still exist.

**Closed by krzychu124** 2022-06-22 19:47 UTC
Labels: EXTERNAL, out of scope, irreproducible
