### ISSUE TITLE
Separate start/end lane connector points for cars and trams on roads where the car and tram lanes overlap

### ISSUE THREAD

**Issue by HypoSim** [CitiesSkylinesMods/TMPE#1015] opened 2020-10-07 22:37 UTC
Currently, the lane connectors for cars amd trams overlap, and separating the car and tram traffic is impossible.

**Comment by krzychu124** [comment] 2020-10-08 21:56
Duplicate of #354 but thanks for reminding us about that problem😉

**Closed** 2020-10-08 21:56 UTC
Labels: LANE ROUTING, duplicate
