### ISSUE TITLE
Shortcut keys standardisation

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#587] opened 2019-12-03 08:05 UTC
I've just added a page to the wiki listing _some_ of the shortcut keys:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Shortcuts

I'd like to propose the following standardisation:

* **`Shift`** - replicate something (between junctions, along a route, ~~around a node~~)
* **`Ctrl`** - Should give more control
    * Example: Speed Limits tool - `Ctrl` toggles between direction vs. lanes
* **`Alt`** - Delivers alternative to the standard functionality
    * Example: Lane Arrows tool - Alt-clicking applies turning lane, rather than selecting the lane for manual customisation
* **`Del`** - Should delete stuff (for whatever is currently selected)
    * Example: Lane Connector tool - `Del` deletes all connectors for selected node

cc: @kvakvs @kianzarrin

**Comment by kvakvs** [comment] 2019-12-03 11:11
Send this to the UI guidelines page
Looks reasonable for now
I'd make a chart of all tools and shortcuts they use to see entire picture, and then draw some conclusions, if some shortcut looks wrong or stands out in a different way to fix it or to update this list.

**Comment by kianzarrin** [comment] 2019-12-03 11:29
>Alt - Delivers alternative to the standard functionality
Example: Lane Arrows tool - Alt-clicking applies turning lane, rather than selecting the lane for manual customisation

Then maybe I should modify the quick lane separation shortcuts:
currently: ALT=quick separate segments | CTRL=quick separate node
change to: CTRL+ALT: quick separate segments | ALT quick separate segments
considering click will select a segment it makes sense if CTRL-click does more to a **segment**.
ALT is the alternative quick separate for **node**

**Comment by aubergine10** [comment] 2019-12-03 11:48
For lane arrows, I think it would be better as:

* Alt+Click segment = instead of selecting that segment, it gives it a turning lane
* Shift+Click node = all roads entering node get separated turning lane

**Comment by krzychu124** [comment] 2019-12-03 12:16
It looks good, but as I suggested in #574  we should separate key combination from actual translation of tooltip, because every time we would change it we will have to update every translation for each language.
Key combination confuses translators - you can see that key combination is currently missing on some tooltip translations.

**Comment by kvakvs** [comment] 2019-12-03 12:23
The tooltips with keys are temporary.
The intent is to show current mode shortcuts as a part of TM:PE window or an attach window, and for that i can reuse current tooltip translations and manually remove the key from them without involving translators.

**Comment by krzychu124** [comment] 2019-12-03 12:27
Why not just create separate keys for key modifiers and concatenate it to current tooltip text? Tooltip text will be reusable and key modifier too

**Comment by kvakvs** [comment] 2019-12-03 12:33
That will add strings temporarily which we do not need at the moment, and they will have to be removed later. Also there is no need to translate every keyboard shortcut, but if translators do some, there is no harm in that. I'd say do nothing and keep it like this, by the time we release v11 it will have no keys in tooltips, and the keyboard help will move elsewhere.

**Comment by krzychu124** [comment] 2019-12-03 12:38
The problem is that translators omit that key combination while translating so tooltip is incomplete and then in-game that tooltip doesn't show most important part of information.

**Comment by kvakvs** [comment] 2019-12-03 12:42
Use API in Keybind.cs
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/master/TLM/TLM/State/Keybinds/Keybind.cs#L21-L26
Don't add translation keys.

**Comment by krzychu124** [comment] 2019-12-03 12:51
Ok, so we should fix currently merged features to use this API for shortcuts then.
Doesn't it need `SavedInputKey ` instance to work? In other words input combination that is saved inside keybinds configuration?

**Comment by kvakvs** [comment] 2019-12-03 12:53
You can create SavedInputKey that is not editable in keybinds UI and translate it, even if it is saved does not matter. Or you can follow the code path inside CO.UI and get the calls they use to translate keys.

**Comment by kianzarrin** [comment] 2020-01-23 00:34
#77 is related

**Comment by aubergine10** [comment] 2020-02-09 00:31
Completed a list of (almost) all mouse/keyboard interactions with the tools: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Shortcuts

`Shift` key is very clearly "apply to route" (what defines a route is tool specific).

> Biggest discrepency I can see so far is the old `Shift + S` shortcut for "Straight Ahead" on Lane Connector tool. We should probably change to `Ctrl + S` to be more consistent with other tools.

`Ctrl` key is largely associated with "bulk applicators" (for want of a better phrase).

`Alt` key is only used once, in the Lane Arrows tool.

`Del` and `Backspace` are starting to become standardised in many tools as "reset" (ie. clear custom settings / revert to defaults).

**Closed** 2020-04-22 15:14 UTC
Labels: UI, Usability, discussion
