### ISSUE TITLE
Broken Road Assets page needs updating

### ISSUE THREAD

**Issue by MrYawnie** [CitiesSkylinesMods/TMPE#1038] opened 2020-11-21 17:17 UTC
Hello,

It has been brought to my attention, that you have flagged "All Mr.Yawnie's road assets" as incompatible. However, that is simply not true anymore. I have removed my past assets, and created road asset packs. They have been uploaded in March, and verified working.

Therefore I request you to update your "Broken Roads" under the Wiki, and remove the incompatibility with my mods.

Thank you.

### Steps to reproduce

1. 
2. 
3.

**Comment by chameleon-tbn** [comment] 2020-11-22 07:24
At least i found your stuff on Steam 😊 next time please ad links to your Profile or the assets... Will make my life easier...

I'll test your roads later today.

**Comment by MrYawnie** [comment] 2020-11-22 07:40
Will do, but would also be nice if next time you didn't just blindly and boldly claim other creator's assets are not compatible without informing the author 😉 the issue was fixed long time ago, and I had no way of correcting your page as I had no idea of such claims.On 22 Nov 2020 9.24, Chamëleon <notifications@github.com> wrote:

At least i found your stuff on Steam 😊 next time please ad links to your Profile or the assets... Will make my life easier...

I'll test your roads later today.

**Comment by chameleon-tbn** [comment] 2020-11-22 08:05
If you look into revisions, you'll see that I was not the one who added your roads - I do inform the creators :)

**Comment by MrYawnie** [comment] 2020-11-22 08:18
Good to hear you inform them. Whoever added it, did not inform me though. And also, my name was incorrectly written as well, so I wouldn't even find it should I search for it.

**Comment by chameleon-tbn** [comment] 2020-11-22 13:34
So, i had now time to check all of your roads. 
Good News: Only one throw the `BrokenAssetException`
Bad News it is one from the OST2 Stock Road Pack.
`Custom Assets: 1672263805.Basic Road Tunnel0: [BrokenAssetException]`

But a lot have `Duplicate prefab name`^

```
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.MediumBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.MediumBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.LargeRoadBridgeSuspensionPillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.LargeRoadBridgeSuspensionPillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayRampPillar: Duplicate prefab name
Custom Assets: 1672263805.RoadSmallBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayRampPillar: Duplicate prefab name
Custom Assets: 1672263805.RoadSmallBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayRampPillar: Duplicate prefab name
Custom Assets: 1672263805.RoadSmallBridgePillar: Duplicate prefab name
Custom Assets: 2014220858.Two Lane Highway Bridge Pillar: Duplicate prefab name
Custom Assets: 2014220858.Two Lane Highway Suspension Pillar: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Tunnel0: Duplicate prefab name [BrokenAssetException]
```

For Pillars it is not a big issue, but for the Elevations it is.

### What does it mean and whot will it do ingame?
`Pillar: Duplicate prefab name` --> Same Pillar used for different roads --> as long as they are optical the same, this will only throw the 'error' but will not hurt the game. But of course it shows not clean work in road creation and players will ask about this error again and again.

`Elevated0,Bridge0,Slope0,Tunnel0: Duplicate prefab name` -> same of this is used --> as long as they are optical the same, this will only throw the 'error' but will not hurt the game. But if anything is changed at these elevations it will not work as expected. It will be only used one version of them ingame - which one is random. This error is caused by copy a road and not take care to rename the internal name of the elevations correctly for each single road. But of course it shows not clean work in road creation and players will ask about this error again and again.

`[BrokenAssetException]` --> as the name says: Broken! --> This can hurt the game in various ways: Not working road, not correctly driving vehicles, road not showing up in game menu, broken graphics and yes with some mods together they can even be the reason for a game crash. Reason of this error? Various: missing dependencies, missing/wrong/broken LOD, missing texture/wrong/broken texture and a lot of more....

For the moment i will change the text in the broken list to 1672263805 only.

**Comment by MrYawnie** [comment] 2020-11-22 13:48
Thank you.I will take a look into them later when I have the time. I'm new with modding, and have not played C:S in a long time. Good to hear some explanations for a more seasoned modder! And thanks for editing the post. Cheers! On 22 Nov 2020 15.34, Chamëleon <notifications@github.com> wrote:
So, i had now time to check all of your roads.
Good News: Only one throw the BrokenAssetException
Bad News it is one from the OST2 Stock Road Pack.
Custom Assets: 1672263805.Basic Road Tunnel0: [BrokenAssetException]
But a lot have Duplicate prefab name^
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.MediumBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.MediumBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.LargeRoadBridgeSuspensionPillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.LargeRoadBridgeSuspensionPillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayRampPillar: Duplicate prefab name
Custom Assets: 1672263805.RoadSmallBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayRampPillar: Duplicate prefab name
Custom Assets: 1672263805.RoadSmallBridgePillar: Duplicate prefab name
Custom Assets: 1672263805.HighwayRampPillar: Duplicate prefab name
Custom Assets: 1672263805.RoadSmallBridgePillar: Duplicate prefab name
Custom Assets: 2014220858.Two Lane Highway Bridge Pillar: Duplicate prefab name
Custom Assets: 2014220858.Two Lane Highway Suspension Pillar: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Medium Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Large Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Tunnel0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Elevated0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Bridge0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Slope0: Duplicate prefab name
Custom Assets: 1672263805.Basic Road Tunnel0: Duplicate prefab name [BrokenAssetException]

For Pillars it is not a big issue, but for the Elevations it is.
What does it mean and whot will it do ingame?
Pillar: Duplicate prefab name --> Same Pillar used for different roads --> as long as they are optical the same, this will only throw the 'error' but will not hurt the game. But of course it shows not clean work in road creation and players will ask about this error again and again.
Elevated0,Bridge0,Slope0,Tunnel0: Duplicate prefab name -> same of this is used --> as long as they are optical the same, this will only throw the 'error' but will not hurt the game. But if anything is changed at these elevations it will not work as expected. It will be only used one version of them ingame - which one is random. This error is caused by copy a road and not take care to rename the internal name of the elevations correctly for each single road. But of course it shows not clean work in road creation and players will ask about this error again and again.
[BrokenAssetException] --> as the name says: Broken! --> This can hurt the game in various ways: Not working road, not correctly driving vehicles, road not showing up in game menu, broken graphics and yes with some mods together they can even be the reason for a game crash. Reason of this error? Various: missing dependencies, missing/wrong/broken LOD, missing texture/wrong/broken texture and a lot of more....
For the moment i will change the text in the broken list to 1672263805 only.

**Comment by chameleon-tbn** [comment] 2020-11-22 13:51
if you need further help feel free to contact me over discord or steam... my discord is available on my steam profile. I'll close this issue now.

**Closed** 2020-11-22 13:59 UTC
Labels: BUG, triage
