### ISSUE TITLE
Lane connector changes keep deleting after re-loading saved world

### ISSUE THREAD

**Issue by MaximumDesigns** [CitiesSkylinesMods/TMPE#808] opened 2020-04-01 01:20 UTC
Hi there.

I've noticed that each time I use the TMPE lane connector tool, after re-loading in the world, all of the changes I've made disappear. 

I'm using the latest LABS addition.

**Comment by aubergine10** [comment] 2020-04-01 01:24
First, check to see if you have any incompatible mods:
https://steamcommunity.com/sharedfiles/filedetails/?id=2034713132

If still having problems after checking mods, please provide the log files / save game so we can do some testing:
https://github.com/CitiesSkylinesMods/TMPE/wiki/Report-a-Bug

**Comment by Xyrhenix** [comment] 2020-04-01 01:28
Could you confirm that you're not subscribed to ANY other version of TM:PE? This is often a symptom of being subscribed to multiple versions, even if those other versions aren't enabled.

If you **are** only subscribed to one version of TM:PE, please send your output log and TM:PE log. You can find out where to get those [here](https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Cities-Skylines-log-file).

**Comment by MaximumDesigns** [comment] 2020-04-01 14:00
Hi there,

No mods are incompatible, that part is all good. - There was another version of TM:PE, which wasn't enabled. I removed it, restarted computer, tested, error still occurred.

Below is the log file / save as requested. 

https://steamcommunity.com/sharedfiles/filedetails/?id=2043540808
& logfile: https://drive.google.com/file/d/1GAXpi6SX3_RFVMWkDgdA-VwcDhVwyN7b/view?usp=sharing

**Comment by krzychu124** [comment] 2020-04-01 14:08
Hi, `Improved Assets Panel` is causing an error. Unsubscribe https://steamcommunity.com/sharedfiles/filedetails/?id=417430545

>  There was another version of TM:PE, which wasn't enabled. 

That's the cause of not saving/loading `TM:PE` settings.

**Comment by krzychu124** [comment] 2021-07-31 01:14
Pretty common problem, link to the log is dead. Closing for now.

**Closed by krzychu124** 2021-07-31 01:14 UTC
Labels: awaiting feedback
