### ISSUE TITLE
Black Woods red cars glitch

### ISSUE THREAD

**Issue by tstivers1990** [CitiesSkylinesMods/TMPE#1101] opened 2021-05-05 10:42 UTC
Start a new game with TM:PE enabled and select the Black Woods map.

Lay some roads out like this:
![image](https://user-images.githubusercontent.com/14251176/117129452-b0402880-ad6c-11eb-8673-36d358842efa.png)

Eventually, some red cars will come along and park somewhere, like this, with no owner:
![image](https://user-images.githubusercontent.com/14251176/117129504-c2ba6200-ad6c-11eb-8674-885d16480cdb.png)

This happens with only TM:PE enabled. I don't know if it's specific to Black Woods or not, but I haven't noticed it on other maps and the various reports on the internet have said they only notice it on Black Woods. I've tried to reproduce it without TM:PE and wasn't able to. Clear vehicles doesn't clear the red vehicles. Restricting parking will move them around and if you leave nowhere for them to park, they'll all be gone. But some of them come back when you re-enable parking.

**Comment by tstivers1990** [comment] 2021-05-05 10:51
It seems to happen immediately after placing a road piece. Remove parked vehicles does clear them.

**Comment by krzychu124** [comment] 2021-05-05 23:28
Hmm It's weird, vehicles spawned but I could easily remove them using "remove parked vehicles" button from the Maintenance tab. _Investigating..._

**Comment by krzychu124** [comment] 2021-05-06 18:28
Ok, I found the cause... It's not the mod bug. 

That map has 327 parked vehicles waiting to relocate (game tries to relocate parked vehicles on each network update). 

![image](https://user-images.githubusercontent.com/19638970/117347196-1205ad00-aea9-11eb-8760-a730f3661e0f.png)

**Comment by tstivers1990** [comment] 2021-05-07 11:59
Submitted a bug report to Paradox: https://forum.paradoxplaza.com/forum/threads/cities-skylines-steam-black-woods-red-cars.1472766/

**Comment by krzychu124** [comment] 2021-07-30 20:54
I'll close this issue since it's outside of **TM:PE** scope _(game bug)_

**Closed by krzychu124** 2021-07-30 20:54 UTC
Labels: Annoyance, EXTERNAL, PARKING
