### ISSUE TITLE
Parking AI broken after Campus Update

### ISSUE THREAD

**Issue by Diamity** [CitiesSkylinesMods/TMPE#352] opened 2019-06-02 06:25 UTC
### Description
Cars no longer look for parking spots on Parking Lot Roads and Parking Garages (such as the recently released University Parking Garage by KingLeno). Cars still park on regular roadside parking as usual. This started to occur after the Campus update. When loading a pre-Campus save with existing parked cars using the Parking AI, updating the parking spots in any form (such as moving the height on MoveIt with Page Up) will cause all the cars to disappear without a trace. Roadside parking updates as normal. There also seems to be an issue where cars disappear one by one even without any actions. Of course, Parking AI is enabled in the TM:PE settings; global configuration has been reset multiple times with no effect. There is a video that shows the effects of this bug.

### Reproduction Steps
1. Load a pre-Campus save with existing cars parked in Parking Lot Roads/Parking Garages.
2. Update the parked cars by moving/adjusting a nearby node using MoveIt.
3. Cars disappear without a trace.

### Mod List
- TM:PE 10.20
- 81 Tiles (Fixed for C:S 1.2+)
- Achieve It!
- Adaptive Prop Visibility Distance
- Additive Shader
- Advanced Stop Selection
- Advanced Vehicle Options
- AnimUV Params
- Automatic Bulldozer
- Building Anarchy
- Building Eyedropper Tool
- Building Panel Already Exists
- Camera Positions Utility
- Cargo Hold Fix
- CSL Map View
- Custom Animation Loader
- Daylight Classic
- Decal Prop Fix
- Dynamic Resolution
- Environment Changer
- Extra Landscaping Tools
- Extra Train Station Tracks
- Farther Zoom
- Find It! 1.5.4
- Fine Road Anarchy 1.3.5
- Fine Road Tool 1.3.7
- Hide It!
- Improved Public Transport 2 [r4.3.1]
- Klyte Commons
- Less Steam 
- Loading Screen Mod
- LOD Toggler
- More Advanced Toolbar
- Move It 2.4.1
- Network Extensions 2
- No Problem Notifications
- No Radioactive Desert and More!
- NotSoUniqueBuildings
- Parallel Road Tool 1.3.0
- Plop the Growables
- Ploppable Asphalt
- Ploppable RICO
- PollutionRemoverMod
- Precision Enginnering
- Prop & Tree Anarchy
- Prop It Up! 1.4.4
- Prop Line Tool
- Prop Precision 1.0.1
- Prop Snapping
- PropRotatingParams
- Quay Anarchy
- Real Time
- Segment Slope Smoother
- Sharp Textures
- Smart Intersection Builder
- Stop Hider
- Theme Decals
- Theme Mixer
- Touch This! Tool 2.0.2
- Tram Station Track
- Transparency LOD Fix + Cloud Assets Enabler
- Tree Fire Control
- Tree LOD Fix
- Tree Snapping
- UK Roads
- Ultimate Level of Detail
- Unlimited Money
- Unlimited Oil and Ore
- Unlimited Soil
- Unlock All
- Vanilla Trees Remover
- WG Citizen Lifecycle Reblance v2.6

### Output Log
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3244472/output_log.txt)

### Savegame (Optional)
https://steamcommunity.com/sharedfiles/filedetails/?id=1758698168

### Video (Optional)
https://www.youtube.com/watch?v=w6cPFHWxTn8

**Comment by VictorPhilipp** [comment] 2019-06-02 07:33
Expected behavior:
- Moving/Updating a road segment causes 
cars to become redistributed to other road segments: This is expected behavior and implemented in the base game.
- Cars randomly disappear: This also is expected (fallback) behavior in cases when
  - a cim dies
  - (a cim moves to a different location OR a cim gets teleported and) the parked car (becomes/is) unreachable by foot or public transport
  - a tourist leaves the city by any other mode of transport

But Cims not looking for building parking would definitely be an issue. I have not checked yet, but since the Campus DLC doed not modify parking mechanics it could be a mod compatibility issue

**Comment by titanitycs** [comment] 2019-06-02 10:55
Right. After some re-examining it seems that when updating the parked cars inside parking lots, it redistributes them to a roadside parking spot, but once the existing parked cars are gone, no cars ever try to park inside the updated parking lot or parking garage again. I also seem to have cars with the same infinite loop pathfinding bug in #259.
I haven't downloaded any new assets or mods since the 1.12 update, so I guess it could be a mod update that's causing the problem.

**Comment by aubergine10** [comment] 2019-06-02 12:24
> no cars ever try to park inside the updated parking lot or parking garage again

The parking lot assets on those parking lot roads are buildings, as is the parking garage. As such it seems the issue is related to parking spaces within buildings.

Did you place those buildings with the `Building Eyedropper Tool` mod?

**Comment by titanitycs** [comment] 2019-06-02 12:28
No, the Parking Lot Roads (and accompanying parking spaces) were placed straight from the respective tab in the roads menu, the garages with FindIt.

**Comment by VictorPhilipp** [comment] 2019-06-07 21:23
might be a duplicate of #259

**Comment by VictorPhilipp** [comment] 2019-06-10 11:33
On hold until #259 is going live.

**Comment by aubergine10** [comment] 2019-06-26 01:59
#259 has been merged

**Comment by aubergine10** [comment] 2019-08-13 12:12
We've had more reports of parking issues on the Parking Lot Roads: #423

**Closed** 2022-10-03 22:24 UTC
Labels: BUG, duplicate, PARKING, COMPATIBILITY
