### ISSUE TITLE
Luke, vehicles are still despawning...

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#277] opened 2019-04-09 19:07 UTC
> # Temporary workarounds
> * This issue is caused by a base-game bug that causes some pedestrian path nodes to "vibrate" between two heights, which in turn causes pathfinder issues.
> * There is a [new mod which detects and highlights the bugged paths on the map](https://steamcommunity.com/sharedfiles/filedetails/?id=1777173984) - subscribe and enable it
> * When you see a problem path, bulldoze it or use Move It mod to tweak it a bit and it will stop vibrating.

----

![Noooooooooooo!](https://user-images.githubusercontent.com/1386719/58294280-271ec980-7dc1-11e9-9081-0459422abf35.jpg)

> Radieh 22 minutes ago 
> Cars are vanishing after road upgrades and or adding new roads. It was working fine until few days ago, possible after the last upgrade this started to happen.

Tagging #86 and #218

**Comment by krzychu124** [comment] 2019-04-09 21:54
😄 but seriously, I hope this is a joke!

**Comment by aubergine10** [comment] 2019-04-09 23:16
Another user just reported same issue:

> GucciSnack 55 minutes ago 
> @aubergine18 exp same issue as @radieh. I wish this mod was never updated for me at least as it was working perfectly fine before... now i have this huge city and my commercial zones need products, and it took me a while to realize the roads were the issue! 
> GucciSnack 53 minutes ago  
> @aubergine18 here's some helpful info that might also have you re-create the issue. Update a road, then you cant map out bus routes, etc. beyond that updated road

I've asked both for save and log file.

**Comment by kuebel** [comment] 2019-04-21 17:29
Always did this for me since industry DLC.

Deactivating and reactivating "Lane connector" in TM:PE Maintenance options helps, but you have to do it for every road/road group built.

**Comment by Lobocimby** [comment] 2019-05-13 20:46
I've run into the same issue today. As vehicles approach a new/upgraded road they despawn, and public transport lines can't be built on them. Only fixes I've found are saving and restarting the game, or disabling TM:PE.

My save: https://steamcommunity.com/sharedfiles/filedetails/?id=1740610774

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3174758/output_log.txt)

**Comment by krzychu124** [comment] 2019-05-14 22:23
I've checked your save and unfortunately I have to confirm that vehicles despawns after road upgrade. 
Disabling and reactivating lane connector feature seems to resolve problem with pathfinding through modified segments...

I will check tomorrow what is going on there and why that feature state change helps.

**Comment by krzychu124** [comment] 2019-05-15 14:44
@Lobocimby
I think I found what is causing despawn issues. 
It might be strange, but removing/rebuilding that pavement path should resolve vehicle despawn issue
![Zrzut ekranu (181)](https://user-images.githubusercontent.com/19638970/57781980-98a8a900-772b-11e9-92fe-5f373aaacbdc.png)

Now I have to investigate why that particular segment is causing infinite segment update loop.

**Comment by krzychu124** [comment] 2019-05-23 16:17
Another report from Discord channel
[savegame](https://steamcommunity.com/sharedfiles/filedetails/?id=1749465043) + [backup](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3213070/NewSave.zip) if deleted

#### Investigation results:
- affected two pavement path nodes (again):
  - id: 14851,
  - id: 16809
- game itself can't properly update node height, which creates infinite loop,
- removing nodes (or moving using MoveIt) resolved issue with vehicle despawn

@VictorPhilipp any thoughts?

**Comment by aubergine10** [comment] 2019-05-23 18:49
_If it's due to "outside 25 tiles" issue...._

It would be worth investigating how the game applies terrain modifiers to roads. To see what I mean, sub the "Cross the Line" mod which allows building of networks outside of purchased tiles. You'll note that roads sit on an unmodified mesh, the terrain doesn't confirm like it would inside the purchased tiles.

My train of thought (all untested assumptions):

1. Game hard-coded not to apply network terrain modifiers outside 25 tile area
2. Within 25 tile area it first checks if tile is purchased before applying modifiers
3. 81 Tiles mod would have to modify at least (1) and maybe (2)
4. Such patch in 81 Tiles mod probably hasn't been updated ever
5. Some performance tweak made in vanilla game and 81 Tiles overwriting it with older code
6. Result = Node loops

Possibly it's something lurking here: https://github.com/bloodypenguin/cities-skylines-unlimiter-1/blob/master/Areas/FakeNetManager.cs

**Comment by aubergine10** [comment] 2019-05-27 01:45
Just had another user with this issue, asked for save game. He mentioned it was also causing his bus routes to break - so the broken node thing might also cause #244?

**Comment by megatr0n-69** [comment] 2019-05-28 05:44
Hey, I am experiencing this issue and posted in [this](https://steamcommunity.com/app/255710/discussions/0/1768134097428159187/?ctp=2) topic over on steam but here is my save game.  

Save game: https://steamcommunity.com/sharedfiles/filedetails/?id=1753348463 

Hope this helps you guys.

**Comment by krzychu124** [comment] 2019-05-28 17:34
@megatr0n-69 The same problem as in @Lobocimby
I forgor to enable TM:PE when testing your save so I think it's not caused by our mod.
More info + screenshot of node to rebuild later

Quick investigation:
NetManager.UpdateNode(ushort, ushort, int):
- `this.m_nodes.m_buffer[(int)node].m_segment0`
  - `node` = 10926,
  - `m_segment0` = 22327

This node has only one segment connected (maybe that's the problem)

**Comment by aubergine10** [comment] 2019-05-28 20:30
Was it inside the 25 tile area?

**Comment by krzychu124** [comment] 2019-05-28 20:37
Unfortunately, yes (only four tiles bought)😕

**Comment by krzychu124** [comment] 2019-05-29 23:00
Issue seems to be reproducible using Fine Road Anarchy mod.
Unfortunately there must be additional variable which triggers it, because not every time this issue occurs.

Affected Path segments:
- `Pavement Path`,
- `Bicycle Path`
- `Gravel Path`

Note: All of them has only one pedestrian lane

Affected Road segments `Network Extension 2`:
- `Two-Lane Alley` from 
- `One-Lane Oneway`
- `One-Lane Oneway With Two Bicycle Lanes`
- `One-Lane Oneway With Parking`

Note: All of them have two pedestrian lanes

Requirements:
- Path has to be connected to cul-de-sac of segment using `Anarchy mode` from Fine Road Anarchy mod. (without you can't 'connect' both segments) It's not really connection like between road segments because there are two nodes on the intersection of segments (first of pavement path and second of road segment) instead of one shared.
- additional unknown condition 😄 (landform?)

Additional notes:
- moving one of these nodes at intersection (using Move It) fixes issue

I've managed to reproduce issue on the new game
[Savegame](https://steamcommunity.com/sharedfiles/filedetails/?id=1755550212)

Mods used:
- Fine Road Anarchy - trigger of issue - not necessary for loading savegame,
- Network Extensions 2 (affected segments) (maybe that's the issue)

Three intersections - ~~tree~~ two nodes affected by infinite loop
Node ID's:
- 2556
- 13813
~~6243~~ Two Bicycle lanes - not triggering infinite loop after loading savegame

**Comment by aubergine10** [comment] 2019-05-29 23:42
To clarify, the issue is occurring purely with anarchy mod (at least Fine Road Anarchy as tested above) by drawing a ped path (or some NExt2 prefabs) route from or too a cul-de-sac node? (ie. Move It mod is not involved anywhere in that process)

Is it possible to reproduce without NExt2 mod installed? Reason I ask is that NExt2 patches a shed load of stuff in the game to make its roads (which at the time of original development couldn't be created any other way) functional -- it could be bug in NExt2?

**Comment by krzychu124** [comment] 2019-05-30 10:27
I'm going to check it out tonight 😉 

> To clarify, the issue is occurring purely with anarchy mod (at least Fine Road Anarchy as tested above) by drawing a ped path (or some NExt2 prefabs) route from or too a cul-de-sac node? (ie. Move It mod is not involved anywhere in that process)

Yeah, route direction doesn't matter.

I tried connecting ped path to the middle of a segment but it doen't work.
When you extend that road from invalid cul-de-sac, issue persist. 
Only moving or rebuilding/refreshing that invalid node solves the problem (which is odd, BTW)

It seems that something is wrong with those NExt 2 nodes in this case only Tiny but not all. 
I've tested other wider segments(NExt2 and vanill) but I couldn't reproduce that issue. 

Maybe calculation of node height (or height of lane of ped/road segment) has a bug which reveals only when some conditions are met (anarchy enabled, nodes are too close to each other), because PedestrianPathAI.AddLaneConnection() updates node height using height of lane but only when value is different. 
If height was updated additional call to updateNode() is performed which calls vanilla updateSegment() or TMPE updateSegment() if enabled for each segment connected to that node.

I will check old saves again.

**Comment by aubergine10** [comment] 2019-05-30 15:49
If nodes are on top of each other, is it possible that one node updates, causing the other to update, and it just goes round in loop like that - they can't update height because the other node prevents it, but they try anyway?

**Comment by krzychu124** [comment] 2019-05-30 18:29
Nope, I thought about that at first and I guess it's impossible.

In savegame I created you can see two nodes listed, because there we have two pavement paths which the game can't properly setup/update (?not sure what is going on there, to be honest).

Third node was invalid before saving but somehow fixed itself after loading savegame again.

This game is complicated 😅

**Comment by krzychu124** [comment] 2019-05-31 20:14
I was able to reproduce infinite loop using only Move It 😕 

It seems that there is a bug in those NExt2 segments listed above.
I enabled snapping and follow terrain feature but without that 'terrain' thing seems to be even easier.

Here is a quick demonstration how I made it.
[Infinite loop test](https://youtu.be/rRL9wXxFRdM)

It looks like something is invalidating connection all the time but game is trying to connect lanes over and over again.

I've checked other vanilla segments and immediately noticed that when I move ped path node close enough to connect to road segment (like on video above), both segments stays connected until they are too far. 
No re-connection of lanes at all while moving node within connection range

**Comment by aubergine10** [comment] 2019-06-02 02:19
@andreharv: Can you think of anything in NExt2 that would cause what's described above?

**Comment by Semt-x** [comment] 2019-06-03 15:28
Requested save game on the comment section of the TMPE workshop. 
Vehicles disappear on a road section, if it is changed (upgraded or a new connection to a road section). until the game is saved an reloaded. 

https://steamcommunity.com/sharedfiles/filedetails/?id=1759990551

**Comment by krzychu124** [comment] 2019-06-03 20:40
Removing that pavement path segment under blue marker should solve the problem in this case.

![01](https://user-images.githubusercontent.com/19638970/58831151-4f71b800-864c-11e9-935c-08e95517c645.jpg)
![02](https://user-images.githubusercontent.com/19638970/58831152-4f71b800-864c-11e9-96e2-4399127fb20a.jpg)

Node id: `10745` 
Worth noting:
- pavement path segment is connected to Two-way road with Trees in this case .
- node which cause issues was built on uneven terrain. 
- Move It and Fine Road Anarchy were not subscribed...

**Comment by aubergine10** [comment] 2019-06-09 09:10
#369 confirmed as another instance of this issue.

**Comment by aubergine10** [comment] 2019-06-09 09:46
Reported to Paradox as per #369 

https://forum.paradoxplaza.com/forum/index.php?threads/cities-skylines-steam-vibrating-node-replicable-bug.1187861/

**Comment by aubergine10** [comment] 2019-06-11 22:51
There's a thread on Steam with more users reporting this issue.

https://steamcommunity.com/workshop/filedetails/discussion/583429740/1812044473333143083/

I assume there's no benefit asking for more savegames as we can't really do much about it without Paradox/CO input?

**Comment by aubergine10** [comment] 2019-06-14 14:18
Confirmed that CO will be investigating this issue. If you have any additional information that might be of use, add it now :)

**Comment by krzychu124** [comment] 2019-06-14 18:27
@aubergine18#8812 
`NetInfo.m_useFixedHeight : bool ` what does that variable do? Do you have any idea?

I'm asking about that because I figured out that just after regular node update, the game is calling `PedestrianPathAI.AfterTerrainUpdate()`. It looks like this method  resetting node position (`NetManager.MoveNode(ushort, Vector3)` to be precise) which has been set earlier at the beginning of `NetManeger.SimulationStep()` and then marks that node for update. 
Whole update process of checking and updating nodes and segments has to be performed again in the next simulation step. This process will loop until you remove segment or modify terrain in that place before re-building again. 

When I changed that `m_useFixedHeight` value to true, issue magically disappeared (because inside `AfterTerrainUpdate()` node height update was skipped). 
The question is: which feature will be screwed up after that change :smile: 

Sorry for late response.

**Comment by aubergine10** [comment] 2019-06-14 19:25
At a guess, it might be something to do with "make terrain same height as road", like when you choose the ground mode in Fine Road Tool/Anarchy?

I couldn't find anything from the usual sources, but some other stuff mentioning height in relation to networks:

**Build Height**
When building the road, it will be created higher or lower than the player has chosen based on this value.

**Surface Level**
CO states this is the default height for vehicles and pedestrians, although it seems ingame the individual vertical offset for lanes is used instead.

**Water Block Offset**
Used for canal depth (negative) and flood wall height.

**Vertical Offset**
The height position of the lane.

**Use Terrain Height**
Uses terrain instead of lane vertical offset or surface level. Used for ground pedestrian paths.

**Comment by krzychu124** [comment] 2019-06-14 19:54
Extracted from [cslmodding.info](https://cslmodding.info/modtools/)
`m_useFixedHeight`
True for station tracks and depot roads which are part of buildings, so they don't align to the terrain when such buildings are built on uneven terrain.

**Comment by aubergine10** [comment] 2019-06-14 20:24
Ah, so by setting it `true` on a normal node that's not part of building it's basically saying "You just sit right where you are and don't move"...

**Comment by krzychu124** [comment] 2019-06-14 20:32
It's a property of `NetInfo` so it applies to AI of network prefab not just node, I think.

**Comment by Eapin** [comment] 2019-06-17 17:03
Hi - I think I'm experiencing this same issue. I just started play Cities Skylines (had some 35 hours in game when this happened). I'm playing the base game, pretty sure I don't have any of the DLCs downloaded. The two major mods I think I had added were TM and Network Extensions (then a few more asset-based items from workshop [road and rail interchanges]). Was a solution to this ever discovered?

**Comment by krzychu124** [comment] 2019-06-17 17:45
As you can see, finding a solution is complicated. 
You can remove problematic beautification paths(pavement/bicycle/gravel) but it's only temporary fix.
As @aubergine10 said CO will be investigating issue and I hope they'll fix it.

**Comment by aubergine10** [comment] 2019-06-22 11:30
Krzychu has made a new mod that helps detect which paths are bugged and highlight them on the map - for more details see the workshop page below:

https://steamcommunity.com/sharedfiles/filedetails/?id=1777173984

**Comment by aubergine10** [comment] 2019-07-31 18:37
Another thread on steam discussing this issue: https://steamcommunity.com/app/255710/discussions/0/1639792569832779992/

**Comment by aubergine10** [comment] 2019-08-14 21:32
Another user with the problem - **broken nodes detector is not finding the problem though**

https://steamcommunity.com/app/255710/discussions/0/2605804632885276642/?tscn=1565816171

**Comment by aubergine10** [comment] 2019-08-14 23:24
@krzychu124 Here's the save game re: comment above: https://steamcommunity.com/sharedfiles/filedetails/?id=1834966040

**Comment by aubergine10** [comment] 2019-08-15 13:41
Krzychu tested and Broken Nodes Detector did find a broken path in that save. The user did not have the mod active when the save was made so maybe they forgot to enable it?

Also Krzychu found they were using old broken mod called "Advanced Road Anarchy" which is no longer in workshop. I've suggested they unsubscribe/delete it via Content Manager > Mods.

**Comment by krzychu124** [comment] 2021-07-31 00:01
Temporal solution proved its value. Closing for now.

**Closed by krzychu124** 2021-07-31 00:01 UTC
Labels: BUG, EXTERNAL, confirmed, investigating
