### ISSUE TITLE
Unable to unpause game

### ISSUE THREAD

**Issue by Adthrawn** [CitiesSkylinesMods/TMPE#677] opened 2020-02-09 16:44 UTC
v11 has introduced an issue where the game is unable to be played. Test on a new map, the game is not able to be unpaused. This either takes the form of the game showing paused, and clicking the pause button not unpausing, or the game showing as unpaused, but unable to do anything and the vehicles are all stuck. 

No new mods have been introduced. Attached log files
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4177165/output_log.txt)
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4177166/TMPE.log)

**Comment by aubergine10** [comment] 2020-02-09 16:54
Try disabling Roundabout Builder mod - it's currenetly incompatible but we are working on a fix with author of that mod.

> # Roundabout Builder

**Comment by Adthrawn** [comment] 2020-02-09 17:11
I just tried to load a new game with that disabled, same issue. For what it's worth, the dev of Roundabout Builder did put an update yesterday saying it was compatible with v11

> Update: Feb 8 @ 5:33pm
> RELEASE 1.8.0
> 
> - Added full compatibility to TMPE v11
> - Added 'Can Change Lanes at Junction' TMPE policy support

**Comment by aubergine10** [comment] 2020-02-09 18:24
Post a [link to your savegame](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Savegame-on-Steam) and we'll see if we can recreate the problem

**Comment by Adthrawn** [comment] 2020-02-09 18:49
This is on brand new maps, not reloading an existing save. Do you want me to create a save from a new game?

**Comment by krzychu124** [comment] 2020-02-09 20:11
I can see missing dependencies of this asset: 
https://steamcommunity.com/sharedfiles/filedetails/?id=1843040605 
and that seem to be broken: 
https://steamcommunity.com/sharedfiles/filedetails/?id=1813941369
As @aubergine10 said, would be nice, we could recreate your mod/assets configuration to check what is wrong there

**Comment by Adthrawn** [comment] 2020-02-09 20:44
Looks like i'm not able to save either...Game is stuck at "Saving". Are there any mods you can see I should try to disable to see if I can at least become active again?

**Comment by krzychu124** [comment] 2020-02-09 20:57
You should unsubscribe `411095553 Terraform Tool`, extremely broken mod and you don't need it since you have `Extra Landscaping Tools`, then `912329352    Building Anarchy` - broken also, it may at some point break your savegames or throw ton of errors.
I noticed that there is a problem with `Newtonsoft.Json` library (mod dependency - i dunno which one)

**Comment by Adthrawn** [comment] 2020-02-09 21:30
I disabled those two, plus `450877484 ModTools (Fixed for 1.1+)`, that was the only reference to `newtonsoft.json` i saw in the workshop folder. For shits and grins i also loaded a vanilla map instead of one from the workshop. Still no dice. I've added new log files

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4177862/output_log.txt)
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4177863/TMPE.log)

**Comment by aubergine10** [comment] 2020-02-09 21:47
Unsubscribe following mods:

* "No More Purple [Tan]" mod (broken) - try [No readioactive desert and more](https://steamcommunity.com/sharedfiles/filedetails/?id=666425898)
* "Employ Overeducated Workers V2" - obsolete, use Industry 4.0 city/district policy
* "One-Way Street Arrows" - obsolete, game now shows arrows on one-way roads when roads menu is open
* "Advanced Toolbar" - has some bugs; try [Resize It](https://steamcommunity.com/sharedfiles/filedetails/?id=1577882296) instead
    * Looks like you already have Resize It subscribed; so make sure that Advanced Toolbar is completely unsubscribed (don't just disable unwanted mods, completely unsubscribe them)
* "Advanced Vehicle Options 1.8.2" outdated; use the [Industries compatible version](https://steamcommunity.com/sharedfiles/filedetails/?id=1548831935) instead

And unsubscribe any other mods you don't use. Always exit game to desktop after changing mods to flush old code from RAM.

Then, before loading a save, go in to Loading Screen Mod's options screen and enable the three "Safe Mode" options, then load your save.

If that still doesn't work, try removing "Klyte's Electric Roads" mod - there is a slight possibility that it could break TM:PE (should be fixed in recent updates, but might not be).

**Comment by Adthrawn** [comment] 2020-02-09 22:15
I loaded up with all the above unsubscribed, and with Safe Mode, still same.

Also, when Exiting to Desktop, it seems to hang here as well. How long should I let it try to exit?

**Comment by Adthrawn** [comment] 2020-02-09 22:19
![image](https://user-images.githubusercontent.com/13037489/74111144-5ef0bb80-4b60-11ea-8b27-1122cfeb0c2c.png)

**Comment by aubergine10** [comment] 2020-02-09 22:34
Exit to desktop does take a while, for me it takes few minutes with screen black like your screenshot. It depends on speed of your hardware as to how long it takes. Your hardware looks decent so I'd expect it to take less than 5 minutes.

Try disable following mods (then exit to desktop and relaunch before loading save):

```
  * 543722850    Network Skins
  * 1440928803   Parallel Road Tool 1.3.0
  * 554763781    No Tree Brush Slope Limit
  * 1249000709   Japanese Railway Crossings
  * 809633246    Japanese Traffic Lights
  * 928128676    Improved Public Transport 2 [r4.4.0]
  * 725555912    Infinite Goods
  * 523818382    Force Level Up -- possible this one is broken as it's very old
  * 409776678    Demand Master
    1625704117   Roundabout Builder -- possible still issue with this, we need more testing
```

If that fixes it then it's one of those mods and you'll have to re-enable one at a time to find out which (please let us know in that case).

If still problems, please attach new log files (output_log.txt and TMPE.log).

**Comment by Adthrawn** [comment] 2020-02-09 23:43
![image](https://user-images.githubusercontent.com/13037489/74112583-fd364e80-4b6b-11ea-92c7-978268debce5.png)
still running. is it ok to kill it at this point?

**Comment by aubergine10** [comment] 2020-02-09 23:56
Yeah, if it's taking that long kill the process.

**Comment by Adthrawn** [comment] 2020-02-10 00:07
Ubsubscribed/disabled all those mods, still not working. 

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4178323/output_log.txt)
[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4178324/TMPE.log)

**Comment by Adthrawn** [comment] 2020-02-10 21:00
I turned off everything except TMPE, and the game launched fine. I'm going to enable mod at a time and see when it fails. Unfortunate seems to be the only way to diagnose what is causing the problem. I'll report back when i found the issue

**Comment by krzychu124** [comment] 2020-02-10 21:12
I would start from `Additive Shader`, `Vehicle Effects` and `Rayilway Replacer`, because other mods doesn't scan your assets.

**Comment by Adthrawn** [comment] 2020-02-10 22:33
I think I may have found the mod causing problems. I'm still checking the rest of my list, but `1764208250 More Vehicles` turned off got the game to run, when enabling mods in chunks. I'll report back soon.

**Comment by Adthrawn** [comment] 2020-02-10 23:04
Ok, I've come back and enabled the rest of the mods and it looks like More Vehicles was the issue. I was able to load a map with everything else.

**Comment by krzychu124** [comment] 2020-02-10 23:05
Thanks, I will try `More Vehicles` and report back.

**Comment by aubergine10** [comment] 2020-02-11 00:21
Tagging @dymanoid

**Comment by aubergine10** [comment] 2020-02-17 14:20
We've had reports that "Pause On Load" mod (or similar mods that allow game to pause when it first loads) have been broken by the recent "Paradox Launcher" update. If you have mod that pauses game after loading a city, try removing that mod and see if that fixes it.

**Comment by aakoch** [comment] 2020-04-20 19:11
I've been having similar issues. I just tried unselecting the "pause on load" option now available with **no** mod and it worked -- I am able to load my city now.

**Comment by dymanoid** [comment] 2020-04-20 19:32
The issue was most probably caused by the Metro Overhaul Mod that conflicted with More Vehicles. It should be working now.

**Comment by krzychu124** [comment] 2020-04-20 19:45
If you are running linux or macos, issue is known, but we still have no idea why this happening, perhaps Harmony issue :/  https://github.com/CitiesSkylinesMods/TMPE/issues/817
I tried it myself on Manjaro Linux with **only TM:PE** subscribed and enabled and I've got similar results: either game crash to desktop or complete simulation lockup.

**Comment by aakoch** [comment] 2020-04-20 22:02
@dymanoid I'm not familiar with either of those mods. (In other words, I don't have them.)

@krzychu124 Yes, I'm on a Mac. I didn't know there was a TMPE.log file so I'll see if it has anything.

**Comment by aubergine10** [comment] 2020-04-20 23:11
Location of TMPE log on Mac/Linux: https://github.com/CitiesSkylinesMods/TMPE/wiki/TMPE.log

**Comment by krzychu124** [comment] 2020-11-13 03:15
Lack of response, closing.

**Closed by krzychu124** 2020-11-13 03:15 UTC
Labels: EXTERNAL
