### ISSUE TITLE
Vehicle restrictions can break cemetery emptying

### ISSUE THREAD

**Issue by Owlchemist** [CitiesSkylinesMods/TMPE#780] opened 2020-03-07 19:27 UTC
### Describe the problem

I used the vehicle restriction tool to prevent my hearses from leaving a district (applied to all chokepoint entrances leading into/out of a the district). At first it seemed to work, until they try to empty to a crematorium.

From what I could tell studying the behavior, the cemetery will randomly select a crematorium. If it selects one it can path to, it will spawn. If it cannot, it will spawn and immediately unspawn, wasting a second or two of time. Since only 1/4th of my crematoriums were reachable, the cemetery would sit around wasting most of its time trying to spawn vehicles.

Now, this isn't exactly a bug specific to TMPE and is just vanilla behavior. However TMPE's vehicle restriction feature arguably graduates the vanilla problem from being a rare niche behavior to potentially becoming more common and troublesome. Something to consider.

### Steps to reproduce

1. Use vehicle restrictions to prevent a cemetery from being able to reach one crematorium, but not all crematoriums.
2. Let it empty and watch it's vehicle spawning figures act strangely.

### Notes or questions?

Not confirmed, but I'm guessing landfills would have this same problem.

**Comment by krzychu124** [comment] 2022-06-22 20:16
You should use one of the mods for restricting service vehicles to selected district(s), restricting just roads is not a solution because target buildings are selected based on needs, and selection process does not take into account reachability via road (it assumes they will be, by design). Closing.

**Closed by krzychu124** 2022-06-22 20:16 UTC
Labels: wontfix
