### ISSUE TITLE
Exception on saving an asset in Asset Editor ~~if it is not an intersection~~

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#1313] opened 2022-01-25 18:07 UTC
### Describe the problem
The user reported issue that creating parking spot asset in the Asset Editor fails to save

```cs
System.NullReferenceException: Object reference not set to an instance of an object
at TrafficManager.State.Asset.AssetData.GetPathsNetworkIDs (.BuildingInfo prefab) [0x00000] in <filename unknown>:0
at TrafficManager.State.Asset.AssetData.GetAssetData (.BuildingInfo prefab) [0x00000] in <filename unknown>:0
at TrafficManager.Lifecycle.AssetDataExtension.OnAssetSavedImpl...
```

### Steps to reproduce (not confirmed yet)

1. Open Asset Editor
2. ~~Try creating asset of different type than intersection~~
3. Check log for errors after asset save

**Comment by aubergine10** [comment] 2022-03-13 21:44
Looks like another user with same error: https://steamcommunity.com/workshop/filedetails/discussion/1637663252/3193619419617966826/

**Comment by kianzarrin** [comment] 2022-03-13 23:20
If I can reproduce it I can fix it.

**Comment by krzychu124** [comment] 2022-03-25 23:32
@kianzarrin in the Asset editor try creating building, select anything as a base but add at least one sub-building e.g. plop it with FindIt then save the asset.

**Comment by kianzarrin** [comment] 2022-03-26 02:06
Oh so no networks

**Comment by kianzarrin** [comment] 2022-04-02 10:11
@krzychu124 are you working on this?
if not can you please assign it to me?

**Comment by krzychu124** [comment] 2022-04-02 16:16
@kianzarrin I could investigate and try to fix it, but if you have more time go on, you can take it 😄

**Comment by kianzarrin** [comment] 2022-04-02 19:42
my guess is if there are zero segments then we should not `serialize` anything. that would fix the problem.

**Closed** 2022-04-03 06:20 UTC
Labels: BUG, Asset Editor
