### ISSUE TITLE
Remove Crosswalk decals when crosswalk disabled

### ISSUE THREAD

**Issue by FireController1847** [CitiesSkylinesMods/TMPE#27] opened 2019-02-04 05:19 UTC
I know we can disable crosswalks programmatically, but it doesn't remove it from the road junction itself. Is that possible?

Somewhat leaving this for future note, also somewhat leaving this for my own purposes.

**Comment by aubergine10** [comment] 2019-02-04 14:23
The Junction Restrictions allow you to disable individual crossings and junctions, but the stripe decals still remain.

I assume you mean the stripe decals should also disappear?

Those decals are triggered by a flag on the road prefab instance IIRC. So in theory changing that flag should make them disappear?

I've seen mods that remove all the crossing decals, which I assume they just delete them from the prefab definitions or something during game load?

But what would be ideal is to find out what causes the game to toggle the decals on and off at junctions, and modify that so that if Junction Restrictions have disabled a crossing then that individual crossing should have its decal removed.

Note: Traffic lights (especially timed ones) also need to account for the removal of a crossing, as does the pathfinder.

**Comment by FireController1847** [comment] 2019-02-04 22:21
Yeah, that's what I meant. The striped decals should disappear.

**Comment by krzychu124** [comment] 2019-02-05 00:08
I am not sure if we can remove them but replacing with transparent blank decal could be easier. I will try to find in code where and how these decals are selected and rendered.

**Comment by Sipke82** [comment] 2019-02-08 07:35
Just plopable asphalt?

**Comment by aubergine10** [comment] 2019-02-08 11:49
Ploppable asphalt needs careful positioning to avoid it overlapping other road parts of the road texture, such as 'stop lines'.

**Comment by FireController1847** [comment] 2019-02-14 20:12
Possible addition to the feature, often times in the U.S. people are allowed to cross even without the crosswalk lines being painted on the road. It's be awesome if we could make crosswalk lines optional in it's entirety.

**Comment by aubergine10** [comment] 2019-02-14 20:26
So the three states would be:

Crosswalk | Decal
--- | ---
✔|✔
✔|❌
❌|❌

**Comment by aubergine10** [comment] 2019-03-02 01:29
This mod, although broken, apparently found a way to hide the crosswalk decals at junctions (but not at tunnels): https://steamcommunity.com/sharedfiles/filedetails/?id=1147015481

**Comment by aubergine10** [comment] 2019-03-29 15:49
Boformer has indicated he might have a way to remove the crossing decals _per segment_. He's working on a new version of Network Skins. IMO we should collaborate as we can already achieve removal of the 'path' part of it but not the visual, and network skins will be the opposite - removing visual but not path.

**Comment by aubergine10** [comment] 2019-03-29 15:54
![boformer](https://user-images.githubusercontent.com/1386719/55245353-dc5a5880-523a-11e9-88db-a531100b434f.png)

**Comment by aubergine10** [comment] 2019-04-06 00:54
From #129:

> "Ach hier hast du mich kontaktiert. :-D
>  
> Ja, so ein Feature wäre prinzipiell nicht verkehrt. Ich selbst habe mit Texturen noch nicht gearbeitet. Ich kann mir vorstellen, dass es einiges an Arbeit kosten wird, Texturen für sämtliche Straßentypen zu erstellen.
>  
> Wenn du abfragen willst, ob Fußgänger an einem Segment/Knoten die Straße überqueren können, kannst du die Methode JunctionRestrictionsManager.Instance().IsPedestrianCrossingAllowed(ushort segmentId, bool startNode) nutzen. segmentId ist die Id des Segments und startNode gibt an, ob du den Fußgängerüberweg am Startknoten (true) oder am Endknoten (false) meinst.
>  
> Wie würden die Mods denn miteinander kommunizieren können? Über Reflection oder gibt's da einen eleganteren Weg?"

**Comment by FireController1847** [comment] 2019-04-06 03:40
From #129 (translated):
> Oh, here you contacted me. :-D
> 
> Yes, such a feature would not be wrong in principle. I myself have not worked with textures yet. I imagine it will take a lot of work to create textures for all road types.
> 
> If you want to know if pedestrians can cross the road on a segment / node, you can use the JunctionRestrictionsManager.Instance (). IsPedestrianCrossingAllowed (ushort segmentId, bool startNode) method. segmentId is the id of the segment and startNode indicates whether you mean the pedestrian crossing at the start node (true) or at the end node (false).
> 
> How would the mods communicate with each other? About Reflection or is there a more elegant way?

**Comment by aubergine10** [comment] 2019-12-08 15:03
Kian is close to having solution for this: https://github.com/kianzarrin/myrepo/issues/1

**Comment by kianzarrin** [comment] 2019-12-11 10:04
Can we close this. I have posted this mod that fixes this issue:
https://steamcommunity.com/sharedfiles/filedetails/?id=1934023593

**Comment by aubergine10** [comment] 2019-12-11 12:50
Once it merges in to NS2.

**Comment by aubergine10** [comment] 2019-12-11 13:11
From my comment in Discord:

> It should certainly be in NS2 as lots of TM:PE users, including myself, use NS2. I suspect NS2 could also elaborate on the functionality, eg. allowing any or all crossings to be hidden purely for aesthetic purposes (eg. the actual crossing remains as far as pathfinder is concerned, but the visual element is removed).
>  
> However, I'd like to see the basic functionality in TM:PE also as it should hide disabled (via Junction Restrictions tool) crossings regardless of whether NS2 is active or not. The TM:PE version of it would deactivate if any version of Network Skins (1 or 2) or is active, or any mod conflict (patch collision) detected.

**Comment by aubergine10** [comment] 2019-12-11 13:32
> **Kian:** We can merge this into TMPE later. Although I do not think its a good idea since TMPE is not supposed to deal with textures. Also might create incompatibility issues with other mods. 

While not the primary goal of TM:PE, it's been long-standing feature request (eg: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/16) from users and it's regularly been mentioned in various suggestion/improvement threads over the years, so there is user expectation that when crossing is disabled in TM:PE the visual stuff on the road should update.

Similarly, there's also the stuff about speed limit sign props - where users have asked if we can make those reflect the speed set by TM:PE speed limit too. (see: #49, #124 for some recent discussion on that).

Also, we already alter lane arrows when TM:PE changes lane routing at junctions, so there is some precedent of us altering or affecting the visible stuff on the map.

**Comment by kianzarrin** [comment] 2019-12-11 13:59
@aubergine10 
what are you going to do about compatibility issues with NS2? maybe we an say if NS2 is loaded then do not patch NetNode.RenderInstance()?

PS:I talked to NS2 last night and he said he likes to merge my mod as it is into his mod (it will use harmony though). And he has future plans to create user UI that generates Network skins without crosswalks.

**Comment by aubergine10** [comment] 2019-12-11 14:01
> what are you going to do about compatibility issues with NS2? maybe we an say if NS2 is loaded then do not patch NetNode.RenderInstance()?

Yes, precisely that. 

We check to see if any NS mod (v1 or 2, assuming they both update the `NetNode.RenderInstance()`) is enabled, and if so we don't apply our patch and NS2 does the work.

cc: @boformer

**Comment by aubergine10** [comment] 2019-12-11 14:04
The only possible issue I foresee is if users start getting confused that hiding crosswalk in NS2 doesn't 'disable' the actual pedestrian crossing.

**Comment by kianzarrin** [comment] 2019-12-12 10:13
@aubergine10 @boformer How should we have both NS2 and TMPE to remove crossings without having too much duplicate code? 
This will be more important in future as I suspect both TMPE and NS2 would like to do more road texturing. TMPE for one is developing a taste for it! I can feel it! see #557

**Comment by Sipke82** [comment] 2019-12-12 10:28
In my opinion texture changes caused by TMPE adaptions, should be performed by TMPE.

**Comment by kianzarrin** [comment] 2019-12-12 11:30
@Sipke82 
That is easier said than done because there are compatibility issues. So for example NS2 might want to use rainbow crosswalks (presumably by hiding original crosswalks and adding rainbow prop). while TMPE might want to hide crosswalks. They both need to patch the same line of NetNode.RenderInstance().

**Comment by aubergine10** [comment] 2019-12-12 11:46
A shared git module perhaps?

**Comment by krzychu124** [comment] 2019-12-12 19:04
There are two main cases and two additional if you want to separate logic through both mods:
1. NS2 installed
2, NS2 not installed.
3, N

**Comment by krzychu124** [comment] 2019-12-12 19:33
There are few cases to cover. The best option would be to separate responsibility (TMPE - manages paths, NS2 - manages textures). Use observer pattern or similar to notify about changes.
1. new game, both mods installed - both mods are connected via simple observer API, any change in one mod is propagated to the other, works in both directions + additional configuration (update paths when crosswalk is shown/hidden using NS2 or TMPE disabling/enabling pedestrian crossing should update textures - managed by NS2)
2. NS2 not installed (TMPE manages textures by itself) - easiest case, I think

Synchronization problems to solve. I think that will be the hardest part.
1. NS2 installed at later date - what to do with hidden crosswalks? Should we move settings from TMPE to NS2 or not? If yes, how?
2. NS2 installed before TMPE - similar to previous case - what to do with hidden crosswalks, Should we move settings from NS2 to TMPE or not? If yes, how?

**Comment by aubergine10** [comment] 2019-12-12 19:46
If both mods have it there's also the issue of duplicate data in the save (NS2 saving that it's hidden the crossing lines, TM:PE saving that the actual crossing path is disabled).

There's also the issue that a user hiding crossing lines in NS2 might not want the actual crossing path removed (example: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/27#issuecomment-463776034).

**Comment by FireController1847** [comment] 2019-12-13 01:59
It does not make sense to require another mod to add a functionality this mod should have had in the first place. TM:PE modifies things about traffic, it is not exclusive to the code. There's no reason, compatibility or not, that we should not modify the textures on their own. If I disable a crosswalk using TM:PE, I expect the crosswalk to be disabled entirely, textures as all. Similarly, like stated earlier, if I change the speed limit, I expect the speed limit to be changed, textures and all. It wouldn't make sense to make NS2 as a dependency for this feature; what is somebody doesn't want or use NS2? Then, suddenly we've found ourselves in a position where functionality provided by TM:PE doesn't make sense, as it does currently.

By making it NS2 exclusive, that's like saying when we disable traffic lights, they should not be removed from the junction because "we don't modify textures" unless you install some third-party "road modifier" mod. It's the same concept. If I disable traffic lights, I expect the traffic lights to be disabled, models & textures and all. If I disable crosswalks, I expect the crosswalk texture to be disabled, textures and all.

I don't understand why this is such an issue; we've had compatibility issues in the past. We didn't just shrug off features to other mods, did we? I think that @krzychu124's solution would work well _if NS2 is installed_. If it's not installed, TM:PE needs to handle the texture management. **It does not make sense to have the ability to disable crosswalks if it doesn't even look like they're disabled.** This is the problem in the first place. Making it another mod's responsibility doesn't make sense; it lowers the workload, sure, but then you're creating an extra dependency which will not only cause confusion, but frustration on the user's half because now they need to install an entirely new mod just for this one, simple feature.

Imagine if we had to install a separate mod for every change this mod made. Traffic lights? Well you'll need to install the Advanced Traffic Lights mod, which does way more than you need, but, well, we didn't want to implement the feature ourselves.

Sorry, I'm a little salty about the idea of making this mod depend on another for such a, from the user's perspective, "simple" feature that should've been in TM:PE when the feature was implemented in the first place.

**Comment by FireController1847** [comment] 2019-12-13 02:05
I think @krzychu124 has the best solution: if both mods are installed, then NS2 can handle it, but if not, TM:PE should handle it. It'd make no sense to make the mod an external dependency. If people don't want it installed, then why should TM:PE miss a feature because of it, you know?

I think to solve the synchronization, you should try your best to work with their team to get the mods to work together. If TM:PE is installed first, then it should move them to NS2 as NS2 has a more fleshed out implementation. TM:PE's should be a "backup" per-say.

**Comment by aubergine10** [comment] 2020-04-22 16:32
Kian's crosswalk decal hiding mods which might get merged in to TMPE once we move to Harmony 2 properly:

* https://steamcommunity.com/sharedfiles/filedetails/?id=1934023593
* https://steamcommunity.com/sharedfiles/filedetails/?id=1939169189

Will keep this #27 open until integration.

**Comment by krzychu124** [comment] 2021-07-30 23:56
_Hide crosswalks_ mod will probably be a part of **AR**(Advanced Roads) mod. Closing for now.

**Closed by krzychu124** 2021-07-30 23:56 UTC
Labels: JUNCTION RESTRICTIONS, enhancement, low priority, question
