### ISSUE TITLE
Vechicles don't despawn when hit by water

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1208] opened 2021-11-28 23:03 UTC
### Describe the problem

Steam user Francis reported:

> Vechicles don't despawn when hit by water

This might be unwanted side-effect of no-despawn feature?

### Steps to reproduce

1. Plunge vehicle in to water, eg. tsunami or bulldozed hydro dam
2. Vehicle gets swept away by water, and should subsequently despawn - but don't

### Log files

n/a

### Savegame?

not provided

### Screenshots?

n/a

**Comment by krzychu124** [comment] 2021-11-28 23:22
Question is if they normally despawn while floating (I doubt, reading the code) or when they stop floating -> will be hard to guess if they floated before? I see that SimulationStep for floating only increases blockCounter(main variable used to check if should despawn) and calculates sway/velocity etc.. in general makes vehicle float. Rest of the code is ignored.

Anyways it require simple test build to check what is going on and if there is an issue, test if possible fix works (will be one line of code)

**Comment by aubergine10** [comment] 2021-11-29 01:03
I know in vanilla they do eventually despawn, but never really paid attention to how that was working. I vaguely recollect that they floated for a while and then despawned whilst still in water, or if they somehow ended up back on dry land but not near a road (thus unable to reroute to destination).

**Comment by krzychu124** [comment] 2021-12-03 01:27
### Cannot reproduce the issue.
---

I've tested that in isolation (I created a road, spawned few vehicles then pushed water there). 
Vehicles start floating (`m_flags2` == `Floating)` and `m_blocked` counter goes to 100 then vehicle gets despawned, regardless of TM:PE despawning settings. They are not despawned when they are waiting in front of flooded segments, but that's probably ok.

Sidenote: I see in the code we support despawning when vehicle is floating:
https://github.com/CitiesSkylinesMods/TMPE/blob/3ba62f38035439670716430214e36b45e9607a12/TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs#L1717-L1722
and `maxBlockCounter` holds value of the limit before despawn
https://github.com/CitiesSkylinesMods/TMPE/blob/3ba62f38035439670716430214e36b45e9607a12/TLM/TLM/Patch/_VehicleAI/_CarAI/SimulationStepPatch.cs#L215-L228

There is a mod on the workshop that claims it is compatible with TMPE but also patches the code for despawning. Maybe that's the problem?

**Comment by aubergine10** [comment] 2021-12-03 04:11
Was it the heavy outside traffic mod or something like that?

**Comment by krzychu124** [comment] 2021-12-03 10:51
My little thingy for spawning "dummy" vehicles on demand 😉 Select source lane, target lane (anywhere on the map), vehicle type, type in number of vehicles and.. click start to begin spawning the horde of brainless lemmings 😂

**Comment by aubergine10** [comment] 2021-12-03 19:45
Sry, I meant this:

> There is a mod on the workshop that claims it is compatible with TMPE but also patches the code for despawning. Maybe that's the problem?

**Comment by krzychu124** [comment] 2021-12-03 22:28
I think it was this https://steamcommunity.com/sharedfiles/filedetails/?id=2306554537 but I haven't tested it fully to say it is or it is not compatible 🤷‍♂️

**Comment by aubergine10** [comment] 2021-12-04 02:31
![image](https://user-images.githubusercontent.com/1386719/144693758-8ef435c1-2cd7-460d-8d3b-656fd61265fa.png)

also:

![image](https://user-images.githubusercontent.com/1386719/144693772-b974591d-97ab-4309-8eb6-2e0b418000c2.png)

So unlikely to be that mod that's causing what the user reported (I've also asked the original reporting user to confirm what was happening).

IMO we can probably close this issue for now?

**Comment by krzychu124** [comment] 2021-12-04 02:38
Yeah, we can close it, I have no other ideas what it could went wrong or how to break it 🤷‍♂️

**Closed** 2021-12-04 02:57 UTC
Labels: BUG, irreproducible, DESPAWN TOOLS

**Comment by aubergine10** [comment] 2022-01-03 05:15
So, I just discovered that trying to update hydro dam roads (specifically, unlocking them with Network Multitool) causes castropic failure of the dam, creating an inland tidal wave that wiped out my city and port - flushing lots of vehicles in to the river/sea in the processess. They did in fact despawn as expected with the block counter, so I can confirm this was a non-issue.
